[workspace]
members = [
  "proto",
  "erc20/balances",
  "erc20/balances/tools",
]
resolver = "2"

[workspace.package]
description = "EVM Substreams using Firehose Extended blocks"
edition = "2021"
version = "0.0.0"
license = "Apache-2.0"

[workspace.dependencies]
substreams = "0.7.0"
substreams-abis = { git = "https://github.com/pinax-network/substreams-abis.git", tag = "v1.5.0" }
substreams-ethereum = "0.11.1"
prost = "0.13"
prost-types = "0.13"

[profile.release]
lto = true
