//! Portable output of the independently PB-bound local collector, not a source
//! of checkpoint values or a production event stream. Regenerated by the driver.
use super::{binding, historical, BlockInput};
use crate::calculated_retention::binding::sha;
use anyhow::{ensure, Result};
use serde_json::Value;
pub const BYTES: &[u8] = include_bytes!("../../tests/fixtures/ybc-retention/journal.jsonl");
pub const SHA256: &str = "d7308ab0ba651fc77006c0efadddf65fc4b083a02c2c4034a07e327a789d51a2";
pub const MANIFEST: &[u8] = include_bytes!("../../tests/fixtures/ybc-retention/original-block-manifest.json");
pub const MANIFEST_SHA256: &str = "56397f18ea7371231b261baefb10122c1439e604d130be2cbc97fca598e38ba6";
pub fn verify(bytes: &[u8]) -> Result<Vec<BlockInput>> {
    ensure!(sha(bytes) == SHA256 && sha(MANIFEST) == MANIFEST_SHA256, "journal/original manifest digest");
    let original: Vec<Value> = serde_json::from_slice(MANIFEST)?;
    let inputs: Vec<BlockInput> = std::str::from_utf8(bytes)?
        .lines()
        .map(serde_json::from_str)
        .collect::<std::result::Result<_, _>>()?;
    ensure!(inputs.len() == 1024 && original.len() == 1024, "journal count");
    let mut last = historical::checkpoint(historical::PARENT)?.at;
    for (input, m) in inputs.iter().zip(&original) {
        ensure!(
            input.at.number == last.number + 1
                && input.at.parent_hash == Some(last.hash)
                && input.at.timestamp >= last.timestamp
                && input.at.producer_version == Some(5),
            "journal clock/version"
        );
        ensure!(
            m["block"] == input.at.number && binding::hexword(&m["hash"])? == input.at.hash && m["sha256"] == input.source_sha256,
            "journal original identity"
        );
        last = input.at.clone();
    }
    let end = historical::checkpoint(historical::FINAL)?.at;
    ensure!(
        last.number == end.number && last.hash == end.hash && last.timestamp == end.timestamp,
        "journal final captured clock"
    );
    Ok(inputs)
}
