// @generated by buffa-codegen. DO NOT EDIT.
// source: aave_actions.proto

#[derive(Clone, Debug, Default)]
pub struct EventsView<'a> {
    /// Exactly one row per delivered block.
    ///
    /// Field 1: `clocks`
    pub clocks: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::BlockClockView<'a>,
    >,
    /// Field 2: `actions`
    pub actions: ::buffa::RepeatedView<'a, super::super::__buffa::view::ActionView<'a>>,
}
impl<'a> ::buffa::MessageView<'a> for EventsView<'a> {
    type Owned = super::super::Events;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<super::super::__buffa::view::BlockClockView>(),
                )?;
                view.clocks
                    .push(
                        <super::super::__buffa::view::BlockClockView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<super::super::__buffa::view::ActionView>(),
                )?;
                view.actions
                    .push(
                        <super::super::__buffa::view::ActionView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Events, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Events, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Events {
            clocks: self
                .clocks
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            actions: self
                .actions
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for EventsView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.clocks {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.actions {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.clocks {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for v in &self.actions {
            ::buffa::types::put_len_delimited_header(
                2u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for EventsView<'a> {
    const PACKAGE: &'static str = "aave.actions.v1";
    const NAME: &'static str = "Events";
    const FULL_NAME: &'static str = "aave.actions.v1.Events";
    const TYPE_URL: &'static str = "type.googleapis.com/aave.actions.v1.Events";
}
::buffa::impl_default_view_instance!(EventsView);
::buffa::impl_view_reborrow!(EventsView);
/** Self-contained, `'static` owned view of a `Events` message.

 Wraps [`::buffa::OwnedView`]`<`[`EventsView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`EventsView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct EventsOwnedView(::buffa::OwnedView<EventsView<'static>>);
impl EventsOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(EventsOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            EventsOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Events,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(EventsOwnedView(::buffa::OwnedView::from_owned(msg)?))
    }
    /// Borrow the full [`EventsView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &EventsView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Events {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Exactly one row per delivered block.
    ///
    /// Field 1: `clocks`
    #[must_use]
    pub fn clocks(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::BlockClockView<'_>> {
        &self.0.reborrow().clocks
    }
    /// Field 2: `actions`
    #[must_use]
    pub fn actions(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::ActionView<'_>> {
        &self.0.reborrow().actions
    }
}
impl ::core::convert::From<::buffa::OwnedView<EventsView<'static>>> for EventsOwnedView {
    fn from(inner: ::buffa::OwnedView<EventsView<'static>>) -> Self {
        EventsOwnedView(inner)
    }
}
impl ::core::convert::From<EventsOwnedView> for ::buffa::OwnedView<EventsView<'static>> {
    fn from(wrapper: EventsOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<EventsView<'static>>>
for EventsOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<EventsView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Events {
    type View<'a> = EventsView<'a>;
    type ViewHandle = EventsOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct BlockClockView<'a> {
    /// Field 1: `chain_id`
    pub chain_id: u64,
    /// Field 2: `number`
    pub number: u64,
    /// Field 3: `hash`
    pub hash: &'a [u8],
    /// Field 4: `parent_hash`
    pub parent_hash: &'a [u8],
    /// Field 5: `timestamp`
    pub timestamp: u64,
    /// Field 6: `state_root`
    pub state_root: &'a [u8],
    /// Field 7: `producer_version`
    pub producer_version: u32,
    /// Field 8: `spec_revision`
    pub spec_revision: u32,
    /// Field 9: `package`
    pub package: &'a str,
    /// Field 10: `package_version`
    pub package_version: &'a str,
    /// Field 11: `parameters_sha256`
    pub parameters_sha256: &'a str,
    /// Field 12: `action_count`
    pub action_count: u32,
}
impl<'a> ::buffa::MessageView<'a> for BlockClockView<'a> {
    type Owned = super::super::BlockClock;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.chain_id = ::buffa::types::decode_uint64(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.number = ::buffa::types::decode_uint64(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.hash = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.parent_hash = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp = ::buffa::types::decode_uint64(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.state_root = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.producer_version = ::buffa::types::decode_uint32(&mut cur)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.spec_revision = ::buffa::types::decode_uint32(&mut cur)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.package = ::buffa::types::borrow_str(&mut cur)?;
            }
            10u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.package_version = ::buffa::types::borrow_str(&mut cur)?;
            }
            11u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.parameters_sha256 = ::buffa::types::borrow_str(&mut cur)?;
            }
            12u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.action_count = ::buffa::types::decode_uint32(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::BlockClock, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::BlockClock, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::BlockClock {
            chain_id: self.chain_id,
            number: self.number,
            hash: (self.hash).to_vec(),
            parent_hash: (self.parent_hash).to_vec(),
            timestamp: self.timestamp,
            state_root: (self.state_root).to_vec(),
            producer_version: self.producer_version,
            spec_revision: self.spec_revision,
            package: self.package.to_string(),
            package_version: self.package_version.to_string(),
            parameters_sha256: self.parameters_sha256.to_string(),
            action_count: self.action_count,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for BlockClockView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.chain_id != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.chain_id) as u64;
        }
        if self.number != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.number) as u64;
        }
        if !self.hash.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.hash) as u64;
        }
        if !self.parent_hash.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.parent_hash) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        if !self.state_root.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.state_root) as u64;
        }
        if self.producer_version != 0u32 {
            size
                += 1u64
                    + ::buffa::types::uint32_encoded_len(self.producer_version) as u64;
        }
        if self.spec_revision != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.spec_revision) as u64;
        }
        if !self.package.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.package) as u64;
        }
        if !self.package_version.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.package_version) as u64;
        }
        if !self.parameters_sha256.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.parameters_sha256) as u64;
        }
        if self.action_count != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.action_count) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.chain_id != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.chain_id, buf);
        }
        if self.number != 0u64 {
            ::buffa::types::put_uint64_field(2u32, self.number, buf);
        }
        if !self.hash.is_empty() {
            ::buffa::types::put_shared_bytes_field(3u32, &self.hash, buf);
        }
        if !self.parent_hash.is_empty() {
            ::buffa::types::put_shared_bytes_field(4u32, &self.parent_hash, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(5u32, self.timestamp, buf);
        }
        if !self.state_root.is_empty() {
            ::buffa::types::put_shared_bytes_field(6u32, &self.state_root, buf);
        }
        if self.producer_version != 0u32 {
            ::buffa::types::put_uint32_field(7u32, self.producer_version, buf);
        }
        if self.spec_revision != 0u32 {
            ::buffa::types::put_uint32_field(8u32, self.spec_revision, buf);
        }
        if !self.package.is_empty() {
            ::buffa::types::put_string_field(9u32, &self.package, buf);
        }
        if !self.package_version.is_empty() {
            ::buffa::types::put_string_field(10u32, &self.package_version, buf);
        }
        if !self.parameters_sha256.is_empty() {
            ::buffa::types::put_string_field(11u32, &self.parameters_sha256, buf);
        }
        if self.action_count != 0u32 {
            ::buffa::types::put_uint32_field(12u32, self.action_count, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for BlockClockView<'a> {
    const PACKAGE: &'static str = "aave.actions.v1";
    const NAME: &'static str = "BlockClock";
    const FULL_NAME: &'static str = "aave.actions.v1.BlockClock";
    const TYPE_URL: &'static str = "type.googleapis.com/aave.actions.v1.BlockClock";
}
::buffa::impl_default_view_instance!(BlockClockView);
::buffa::impl_view_reborrow!(BlockClockView);
/** Self-contained, `'static` owned view of a `BlockClock` message.

 Wraps [`::buffa::OwnedView`]`<`[`BlockClockView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`BlockClockView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct BlockClockOwnedView(::buffa::OwnedView<BlockClockView<'static>>);
impl BlockClockOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            BlockClockOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            BlockClockOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::BlockClock,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            BlockClockOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`BlockClockView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &BlockClockView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::BlockClock {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `chain_id`
    #[must_use]
    pub fn chain_id(&self) -> u64 {
        self.0.reborrow().chain_id
    }
    /// Field 2: `number`
    #[must_use]
    pub fn number(&self) -> u64 {
        self.0.reborrow().number
    }
    /// Field 3: `hash`
    #[must_use]
    pub fn hash(&self) -> &'_ [u8] {
        self.0.reborrow().hash
    }
    /// Field 4: `parent_hash`
    #[must_use]
    pub fn parent_hash(&self) -> &'_ [u8] {
        self.0.reborrow().parent_hash
    }
    /// Field 5: `timestamp`
    #[must_use]
    pub fn timestamp(&self) -> u64 {
        self.0.reborrow().timestamp
    }
    /// Field 6: `state_root`
    #[must_use]
    pub fn state_root(&self) -> &'_ [u8] {
        self.0.reborrow().state_root
    }
    /// Field 7: `producer_version`
    #[must_use]
    pub fn producer_version(&self) -> u32 {
        self.0.reborrow().producer_version
    }
    /// Field 8: `spec_revision`
    #[must_use]
    pub fn spec_revision(&self) -> u32 {
        self.0.reborrow().spec_revision
    }
    /// Field 9: `package`
    #[must_use]
    pub fn package(&self) -> &'_ str {
        self.0.reborrow().package
    }
    /// Field 10: `package_version`
    #[must_use]
    pub fn package_version(&self) -> &'_ str {
        self.0.reborrow().package_version
    }
    /// Field 11: `parameters_sha256`
    #[must_use]
    pub fn parameters_sha256(&self) -> &'_ str {
        self.0.reborrow().parameters_sha256
    }
    /// Field 12: `action_count`
    #[must_use]
    pub fn action_count(&self) -> u32 {
        self.0.reborrow().action_count
    }
}
impl ::core::convert::From<::buffa::OwnedView<BlockClockView<'static>>>
for BlockClockOwnedView {
    fn from(inner: ::buffa::OwnedView<BlockClockView<'static>>) -> Self {
        BlockClockOwnedView(inner)
    }
}
impl ::core::convert::From<BlockClockOwnedView>
for ::buffa::OwnedView<BlockClockView<'static>> {
    fn from(wrapper: BlockClockOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<BlockClockView<'static>>>
for BlockClockOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<BlockClockView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::BlockClock {
    type View<'a> = BlockClockView<'a>;
    type ViewHandle = BlockClockOwnedView;
}
/// One decoded Pool event. Fields not carried by the event kind are empty.
/// Identity: (scope, transaction_hash, ordinal). Sort: (scope,
/// transaction_index, ordinal, call_index, log_index).
#[derive(Clone, Debug, Default)]
pub struct ActionView<'a> {
    /// Field 1: `chain_id`
    pub chain_id: u64,
    /// Field 2: `scope`
    pub scope: ::buffa::EnumValue<super::super::Scope>,
    /// Field 3: `transaction_hash`
    pub transaction_hash: &'a [u8],
    /// Field 4: `transaction_index`
    pub transaction_index: u32,
    /// Field 5: `call_index`
    pub call_index: u32,
    /// Field 6: `log_index`
    pub log_index: u32,
    /// Field 7: `block_index`
    pub block_index: u32,
    /// Field 8: `ordinal`
    pub ordinal: u64,
    /// Emitting Pool proxy.
    ///
    /// Field 9: `pool`
    pub pool: &'a [u8],
    /// Caller-assigned epoch of the bound Pool implementation and event family.
    ///
    /// Field 10: `epoch`
    pub epoch: u32,
    /// Field 11: `kind`
    pub kind: ::buffa::EnumValue<super::super::ActionKind>,
    /// Reserve (underlying asset) for supply, withdraw, borrow, repay; the debt
    /// asset for a liquidation; the flash-loaned asset for a flash loan.
    ///
    /// Field 12: `reserve`
    pub reserve: &'a [u8],
    /// Address that initiated the action: `user` for supply, withdraw, borrow;
    /// `repayer` for repay; `liquidator` for a liquidation; `initiator` for a
    /// flash loan.
    ///
    /// Field 13: `actor`
    pub actor: &'a [u8],
    /// Position affected: `onBehalfOf` for supply and borrow, `user` (aToken
    /// owner) for withdraw, `user` (debtor) for repay and liquidation, `target`
    /// for a flash loan.
    ///
    /// Field 14: `beneficiary`
    pub beneficiary: &'a [u8],
    /// Recipient of the underlying: `to` for withdraw; empty otherwise.
    ///
    /// Field 15: `recipient`
    pub recipient: &'a [u8],
    /// Raw amount in the reserve's units: amount, debtToCover for a liquidation,
    /// the flash-loaned amount.
    ///
    /// Field 16: `amount`
    pub amount: &'a str,
    /// Raw `interestRateMode` for borrow and flash loan (2 variable; 1 stable,
    /// deprecated since v3.2; 0 flash loan without debt).
    ///
    /// Field 17: `interest_rate_mode`
    pub interest_rate_mode: u32,
    /// Borrow rate in ray for a borrow.
    ///
    /// Field 18: `borrow_rate`
    pub borrow_rate: &'a str,
    /// Field 19: `use_atokens`
    pub use_atokens: bool,
    /// Liquidation only.
    ///
    /// Field 20: `collateral_asset`
    pub collateral_asset: &'a [u8],
    /// Field 21: `liquidated_collateral_amount`
    pub liquidated_collateral_amount: &'a str,
    /// Field 22: `receive_atoken`
    pub receive_atoken: bool,
    /// Flash loan only: fee in the asset's units.
    ///
    /// Field 23: `premium`
    pub premium: &'a str,
    /// Field 24: `referral_code`
    pub referral_code: u32,
    /// The log survived: succeeded transaction and non-reverted frame, or a
    /// non-reverted system call.
    ///
    /// Field 25: `persisted`
    pub persisted: bool,
}
impl<'a> ::buffa::MessageView<'a> for ActionView<'a> {
    type Owned = super::super::Action;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.chain_id = ::buffa::types::decode_uint64(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.scope = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(&mut cur)?,
                );
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.transaction_hash = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.transaction_index = ::buffa::types::decode_uint32(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.call_index = ::buffa::types::decode_uint32(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.log_index = ::buffa::types::decode_uint32(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_index = ::buffa::types::decode_uint32(&mut cur)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.ordinal = ::buffa::types::decode_uint64(&mut cur)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.pool = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            10u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.epoch = ::buffa::types::decode_uint32(&mut cur)?;
            }
            11u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.kind = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(&mut cur)?,
                );
            }
            12u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.reserve = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            13u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.actor = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            14u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.beneficiary = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            15u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.recipient = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            16u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.amount = ::buffa::types::borrow_str(&mut cur)?;
            }
            17u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.interest_rate_mode = ::buffa::types::decode_uint32(&mut cur)?;
            }
            18u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.borrow_rate = ::buffa::types::borrow_str(&mut cur)?;
            }
            19u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.use_atokens = ::buffa::types::decode_bool(&mut cur)?;
            }
            20u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.collateral_asset = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            21u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.liquidated_collateral_amount = ::buffa::types::borrow_str(
                    &mut cur,
                )?;
            }
            22u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.receive_atoken = ::buffa::types::decode_bool(&mut cur)?;
            }
            23u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.premium = ::buffa::types::borrow_str(&mut cur)?;
            }
            24u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.referral_code = ::buffa::types::decode_uint32(&mut cur)?;
            }
            25u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.persisted = ::buffa::types::decode_bool(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Action, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Action, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Action {
            chain_id: self.chain_id,
            scope: self.scope,
            transaction_hash: (self.transaction_hash).to_vec(),
            transaction_index: self.transaction_index,
            call_index: self.call_index,
            log_index: self.log_index,
            block_index: self.block_index,
            ordinal: self.ordinal,
            pool: (self.pool).to_vec(),
            epoch: self.epoch,
            kind: self.kind,
            reserve: (self.reserve).to_vec(),
            actor: (self.actor).to_vec(),
            beneficiary: (self.beneficiary).to_vec(),
            recipient: (self.recipient).to_vec(),
            amount: self.amount.to_string(),
            interest_rate_mode: self.interest_rate_mode,
            borrow_rate: self.borrow_rate.to_string(),
            use_atokens: self.use_atokens,
            collateral_asset: (self.collateral_asset).to_vec(),
            liquidated_collateral_amount: self.liquidated_collateral_amount.to_string(),
            receive_atoken: self.receive_atoken,
            premium: self.premium.to_string(),
            referral_code: self.referral_code,
            persisted: self.persisted,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for ActionView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.chain_id != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.chain_id) as u64;
        }
        {
            let val = self.scope.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        if !self.transaction_hash.is_empty() {
            size
                += 1u64
                    + ::buffa::types::bytes_encoded_len(&self.transaction_hash) as u64;
        }
        if self.transaction_index != 0u32 {
            size
                += 1u64
                    + ::buffa::types::uint32_encoded_len(self.transaction_index) as u64;
        }
        if self.call_index != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.call_index) as u64;
        }
        if self.log_index != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.log_index) as u64;
        }
        if self.block_index != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.block_index) as u64;
        }
        if self.ordinal != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.ordinal) as u64;
        }
        if !self.pool.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.pool) as u64;
        }
        if self.epoch != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.epoch) as u64;
        }
        {
            let val = self.kind.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        if !self.reserve.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.reserve) as u64;
        }
        if !self.actor.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.actor) as u64;
        }
        if !self.beneficiary.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.beneficiary) as u64;
        }
        if !self.recipient.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.recipient) as u64;
        }
        if !self.amount.is_empty() {
            size += 2u64 + ::buffa::types::string_encoded_len(&self.amount) as u64;
        }
        if self.interest_rate_mode != 0u32 {
            size
                += 2u64
                    + ::buffa::types::uint32_encoded_len(self.interest_rate_mode) as u64;
        }
        if !self.borrow_rate.is_empty() {
            size += 2u64 + ::buffa::types::string_encoded_len(&self.borrow_rate) as u64;
        }
        if self.use_atokens {
            size += 2u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        if !self.collateral_asset.is_empty() {
            size
                += 2u64
                    + ::buffa::types::bytes_encoded_len(&self.collateral_asset) as u64;
        }
        if !self.liquidated_collateral_amount.is_empty() {
            size
                += 2u64
                    + ::buffa::types::string_encoded_len(
                        &self.liquidated_collateral_amount,
                    ) as u64;
        }
        if self.receive_atoken {
            size += 2u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        if !self.premium.is_empty() {
            size += 2u64 + ::buffa::types::string_encoded_len(&self.premium) as u64;
        }
        if self.referral_code != 0u32 {
            size += 2u64 + ::buffa::types::uint32_encoded_len(self.referral_code) as u64;
        }
        if self.persisted {
            size += 2u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.chain_id != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.chain_id, buf);
        }
        {
            let val = self.scope.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(2u32, val, buf);
            }
        }
        if !self.transaction_hash.is_empty() {
            ::buffa::types::put_shared_bytes_field(3u32, &self.transaction_hash, buf);
        }
        if self.transaction_index != 0u32 {
            ::buffa::types::put_uint32_field(4u32, self.transaction_index, buf);
        }
        if self.call_index != 0u32 {
            ::buffa::types::put_uint32_field(5u32, self.call_index, buf);
        }
        if self.log_index != 0u32 {
            ::buffa::types::put_uint32_field(6u32, self.log_index, buf);
        }
        if self.block_index != 0u32 {
            ::buffa::types::put_uint32_field(7u32, self.block_index, buf);
        }
        if self.ordinal != 0u64 {
            ::buffa::types::put_uint64_field(8u32, self.ordinal, buf);
        }
        if !self.pool.is_empty() {
            ::buffa::types::put_shared_bytes_field(9u32, &self.pool, buf);
        }
        if self.epoch != 0u32 {
            ::buffa::types::put_uint32_field(10u32, self.epoch, buf);
        }
        {
            let val = self.kind.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(11u32, val, buf);
            }
        }
        if !self.reserve.is_empty() {
            ::buffa::types::put_shared_bytes_field(12u32, &self.reserve, buf);
        }
        if !self.actor.is_empty() {
            ::buffa::types::put_shared_bytes_field(13u32, &self.actor, buf);
        }
        if !self.beneficiary.is_empty() {
            ::buffa::types::put_shared_bytes_field(14u32, &self.beneficiary, buf);
        }
        if !self.recipient.is_empty() {
            ::buffa::types::put_shared_bytes_field(15u32, &self.recipient, buf);
        }
        if !self.amount.is_empty() {
            ::buffa::types::put_string_field(16u32, &self.amount, buf);
        }
        if self.interest_rate_mode != 0u32 {
            ::buffa::types::put_uint32_field(17u32, self.interest_rate_mode, buf);
        }
        if !self.borrow_rate.is_empty() {
            ::buffa::types::put_string_field(18u32, &self.borrow_rate, buf);
        }
        if self.use_atokens {
            ::buffa::types::put_bool_field(19u32, self.use_atokens, buf);
        }
        if !self.collateral_asset.is_empty() {
            ::buffa::types::put_shared_bytes_field(20u32, &self.collateral_asset, buf);
        }
        if !self.liquidated_collateral_amount.is_empty() {
            ::buffa::types::put_string_field(
                21u32,
                &self.liquidated_collateral_amount,
                buf,
            );
        }
        if self.receive_atoken {
            ::buffa::types::put_bool_field(22u32, self.receive_atoken, buf);
        }
        if !self.premium.is_empty() {
            ::buffa::types::put_string_field(23u32, &self.premium, buf);
        }
        if self.referral_code != 0u32 {
            ::buffa::types::put_uint32_field(24u32, self.referral_code, buf);
        }
        if self.persisted {
            ::buffa::types::put_bool_field(25u32, self.persisted, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for ActionView<'a> {
    const PACKAGE: &'static str = "aave.actions.v1";
    const NAME: &'static str = "Action";
    const FULL_NAME: &'static str = "aave.actions.v1.Action";
    const TYPE_URL: &'static str = "type.googleapis.com/aave.actions.v1.Action";
}
::buffa::impl_default_view_instance!(ActionView);
::buffa::impl_view_reborrow!(ActionView);
/** Self-contained, `'static` owned view of a `Action` message.

 Wraps [`::buffa::OwnedView`]`<`[`ActionView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`ActionView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct ActionOwnedView(::buffa::OwnedView<ActionView<'static>>);
impl ActionOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(ActionOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ActionOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Action,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(ActionOwnedView(::buffa::OwnedView::from_owned(msg)?))
    }
    /// Borrow the full [`ActionView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &ActionView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Action {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `chain_id`
    #[must_use]
    pub fn chain_id(&self) -> u64 {
        self.0.reborrow().chain_id
    }
    /// Field 2: `scope`
    #[must_use]
    pub fn scope(&self) -> ::buffa::EnumValue<super::super::Scope> {
        self.0.reborrow().scope
    }
    /// Field 3: `transaction_hash`
    #[must_use]
    pub fn transaction_hash(&self) -> &'_ [u8] {
        self.0.reborrow().transaction_hash
    }
    /// Field 4: `transaction_index`
    #[must_use]
    pub fn transaction_index(&self) -> u32 {
        self.0.reborrow().transaction_index
    }
    /// Field 5: `call_index`
    #[must_use]
    pub fn call_index(&self) -> u32 {
        self.0.reborrow().call_index
    }
    /// Field 6: `log_index`
    #[must_use]
    pub fn log_index(&self) -> u32 {
        self.0.reborrow().log_index
    }
    /// Field 7: `block_index`
    #[must_use]
    pub fn block_index(&self) -> u32 {
        self.0.reborrow().block_index
    }
    /// Field 8: `ordinal`
    #[must_use]
    pub fn ordinal(&self) -> u64 {
        self.0.reborrow().ordinal
    }
    /// Emitting Pool proxy.
    ///
    /// Field 9: `pool`
    #[must_use]
    pub fn pool(&self) -> &'_ [u8] {
        self.0.reborrow().pool
    }
    /// Caller-assigned epoch of the bound Pool implementation and event family.
    ///
    /// Field 10: `epoch`
    #[must_use]
    pub fn epoch(&self) -> u32 {
        self.0.reborrow().epoch
    }
    /// Field 11: `kind`
    #[must_use]
    pub fn kind(&self) -> ::buffa::EnumValue<super::super::ActionKind> {
        self.0.reborrow().kind
    }
    /// Reserve (underlying asset) for supply, withdraw, borrow, repay; the debt
    /// asset for a liquidation; the flash-loaned asset for a flash loan.
    ///
    /// Field 12: `reserve`
    #[must_use]
    pub fn reserve(&self) -> &'_ [u8] {
        self.0.reborrow().reserve
    }
    /// Address that initiated the action: `user` for supply, withdraw, borrow;
    /// `repayer` for repay; `liquidator` for a liquidation; `initiator` for a
    /// flash loan.
    ///
    /// Field 13: `actor`
    #[must_use]
    pub fn actor(&self) -> &'_ [u8] {
        self.0.reborrow().actor
    }
    /// Position affected: `onBehalfOf` for supply and borrow, `user` (aToken
    /// owner) for withdraw, `user` (debtor) for repay and liquidation, `target`
    /// for a flash loan.
    ///
    /// Field 14: `beneficiary`
    #[must_use]
    pub fn beneficiary(&self) -> &'_ [u8] {
        self.0.reborrow().beneficiary
    }
    /// Recipient of the underlying: `to` for withdraw; empty otherwise.
    ///
    /// Field 15: `recipient`
    #[must_use]
    pub fn recipient(&self) -> &'_ [u8] {
        self.0.reborrow().recipient
    }
    /// Raw amount in the reserve's units: amount, debtToCover for a liquidation,
    /// the flash-loaned amount.
    ///
    /// Field 16: `amount`
    #[must_use]
    pub fn amount(&self) -> &'_ str {
        self.0.reborrow().amount
    }
    /// Raw `interestRateMode` for borrow and flash loan (2 variable; 1 stable,
    /// deprecated since v3.2; 0 flash loan without debt).
    ///
    /// Field 17: `interest_rate_mode`
    #[must_use]
    pub fn interest_rate_mode(&self) -> u32 {
        self.0.reborrow().interest_rate_mode
    }
    /// Borrow rate in ray for a borrow.
    ///
    /// Field 18: `borrow_rate`
    #[must_use]
    pub fn borrow_rate(&self) -> &'_ str {
        self.0.reborrow().borrow_rate
    }
    /// Field 19: `use_atokens`
    #[must_use]
    pub fn use_atokens(&self) -> bool {
        self.0.reborrow().use_atokens
    }
    /// Liquidation only.
    ///
    /// Field 20: `collateral_asset`
    #[must_use]
    pub fn collateral_asset(&self) -> &'_ [u8] {
        self.0.reborrow().collateral_asset
    }
    /// Field 21: `liquidated_collateral_amount`
    #[must_use]
    pub fn liquidated_collateral_amount(&self) -> &'_ str {
        self.0.reborrow().liquidated_collateral_amount
    }
    /// Field 22: `receive_atoken`
    #[must_use]
    pub fn receive_atoken(&self) -> bool {
        self.0.reborrow().receive_atoken
    }
    /// Flash loan only: fee in the asset's units.
    ///
    /// Field 23: `premium`
    #[must_use]
    pub fn premium(&self) -> &'_ str {
        self.0.reborrow().premium
    }
    /// Field 24: `referral_code`
    #[must_use]
    pub fn referral_code(&self) -> u32 {
        self.0.reborrow().referral_code
    }
    /// The log survived: succeeded transaction and non-reverted frame, or a
    /// non-reverted system call.
    ///
    /// Field 25: `persisted`
    #[must_use]
    pub fn persisted(&self) -> bool {
        self.0.reborrow().persisted
    }
}
impl ::core::convert::From<::buffa::OwnedView<ActionView<'static>>> for ActionOwnedView {
    fn from(inner: ::buffa::OwnedView<ActionView<'static>>) -> Self {
        ActionOwnedView(inner)
    }
}
impl ::core::convert::From<ActionOwnedView> for ::buffa::OwnedView<ActionView<'static>> {
    fn from(wrapper: ActionOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<ActionView<'static>>>
for ActionOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<ActionView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Action {
    type View<'a> = ActionView<'a>;
    type ViewHandle = ActionOwnedView;
}
