// @generated by buffa-codegen. DO NOT EDIT.
// source: dex-pool-state.proto

/// Both protocol outputs belong to the same complete block. V2 supplies closing
/// reserves; V3 supplies ordered changes requiring a verified starting state.
/// Neither output establishes pool authenticity or token/price interpretation.
#[derive(Clone, Debug, Default)]
pub struct BlockPoolStateView<'a> {
    /// Field 1: `block_number`
    pub block_number: u64,
    /// Field 2: `block_hash`
    pub block_hash: &'a [u8],
    /// Field 3: `parent_hash`
    pub parent_hash: &'a [u8],
    /// Field 4: `timestamp_seconds`
    pub timestamp_seconds: i64,
    /// Field 5: `timestamp_nanos`
    pub timestamp_nanos: i32,
    /// Field 6: `v2_pools`
    pub v2_pools: ::buffa::RepeatedView<
        'a,
        super::super::super::super::super::uniswap::v2::__buffa::view::PoolCloseView<'a>,
    >,
    /// Field 7: `v3_pools`
    pub v3_pools: ::buffa::RepeatedView<
        'a,
        super::super::super::super::super::uniswap::v3::__buffa::view::PoolChangesView<
            'a,
        >,
    >,
}
impl<'a> ::buffa::MessageView<'a> for BlockPoolStateView<'a> {
    type Owned = super::super::BlockPoolState;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_number = ::buffa::types::decode_uint64(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.block_hash = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.parent_hash = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp_seconds = ::buffa::types::decode_int64(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp_nanos = ::buffa::types::decode_int32(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::super::super::super::uniswap::v2::__buffa::view::PoolCloseView,
                    >(),
                )?;
                view.v2_pools
                    .push(
                        <super::super::super::super::super::uniswap::v2::__buffa::view::PoolCloseView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::super::super::super::uniswap::v3::__buffa::view::PoolChangesView,
                    >(),
                )?;
                view.v3_pools
                    .push(
                        <super::super::super::super::super::uniswap::v3::__buffa::view::PoolChangesView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::BlockPoolState, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::BlockPoolState, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::BlockPoolState {
            block_number: self.block_number,
            block_hash: (self.block_hash).to_vec(),
            parent_hash: (self.parent_hash).to_vec(),
            timestamp_seconds: self.timestamp_seconds,
            timestamp_nanos: self.timestamp_nanos,
            v2_pools: self
                .v2_pools
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            v3_pools: self
                .v3_pools
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for BlockPoolStateView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.block_number != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_number) as u64;
        }
        if !self.block_hash.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.block_hash) as u64;
        }
        if !self.parent_hash.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.parent_hash) as u64;
        }
        if self.timestamp_seconds != 0i64 {
            size
                += 1u64
                    + ::buffa::types::int64_encoded_len(self.timestamp_seconds) as u64;
        }
        if self.timestamp_nanos != 0i32 {
            size
                += 1u64 + ::buffa::types::int32_encoded_len(self.timestamp_nanos) as u64;
        }
        for v in &self.v2_pools {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.v3_pools {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.block_number != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.block_number, buf);
        }
        if !self.block_hash.is_empty() {
            ::buffa::types::put_shared_bytes_field(2u32, &self.block_hash, buf);
        }
        if !self.parent_hash.is_empty() {
            ::buffa::types::put_shared_bytes_field(3u32, &self.parent_hash, buf);
        }
        if self.timestamp_seconds != 0i64 {
            ::buffa::types::put_int64_field(4u32, self.timestamp_seconds, buf);
        }
        if self.timestamp_nanos != 0i32 {
            ::buffa::types::put_int32_field(5u32, self.timestamp_nanos, buf);
        }
        for v in &self.v2_pools {
            ::buffa::types::put_len_delimited_header(
                6u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for v in &self.v3_pools {
            ::buffa::types::put_len_delimited_header(
                7u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for BlockPoolStateView<'a> {
    const PACKAGE: &'static str = "dex.pool_state.v1";
    const NAME: &'static str = "BlockPoolState";
    const FULL_NAME: &'static str = "dex.pool_state.v1.BlockPoolState";
    const TYPE_URL: &'static str = "type.googleapis.com/dex.pool_state.v1.BlockPoolState";
}
::buffa::impl_default_view_instance!(BlockPoolStateView);
::buffa::impl_view_reborrow!(BlockPoolStateView);
/** Self-contained, `'static` owned view of a `BlockPoolState` message.

 Wraps [`::buffa::OwnedView`]`<`[`BlockPoolStateView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`BlockPoolStateView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct BlockPoolStateOwnedView(::buffa::OwnedView<BlockPoolStateView<'static>>);
impl BlockPoolStateOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            BlockPoolStateOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            BlockPoolStateOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::BlockPoolState,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            BlockPoolStateOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`BlockPoolStateView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &BlockPoolStateView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::BlockPoolState {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `block_number`
    #[must_use]
    pub fn block_number(&self) -> u64 {
        self.0.reborrow().block_number
    }
    /// Field 2: `block_hash`
    #[must_use]
    pub fn block_hash(&self) -> &'_ [u8] {
        self.0.reborrow().block_hash
    }
    /// Field 3: `parent_hash`
    #[must_use]
    pub fn parent_hash(&self) -> &'_ [u8] {
        self.0.reborrow().parent_hash
    }
    /// Field 4: `timestamp_seconds`
    #[must_use]
    pub fn timestamp_seconds(&self) -> i64 {
        self.0.reborrow().timestamp_seconds
    }
    /// Field 5: `timestamp_nanos`
    #[must_use]
    pub fn timestamp_nanos(&self) -> i32 {
        self.0.reborrow().timestamp_nanos
    }
    /// Field 6: `v2_pools`
    #[must_use]
    pub fn v2_pools(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::super::super::super::uniswap::v2::__buffa::view::PoolCloseView<'_>,
    > {
        &self.0.reborrow().v2_pools
    }
    /// Field 7: `v3_pools`
    #[must_use]
    pub fn v3_pools(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::super::super::super::uniswap::v3::__buffa::view::PoolChangesView<
            '_,
        >,
    > {
        &self.0.reborrow().v3_pools
    }
}
impl ::core::convert::From<::buffa::OwnedView<BlockPoolStateView<'static>>>
for BlockPoolStateOwnedView {
    fn from(inner: ::buffa::OwnedView<BlockPoolStateView<'static>>) -> Self {
        BlockPoolStateOwnedView(inner)
    }
}
impl ::core::convert::From<BlockPoolStateOwnedView>
for ::buffa::OwnedView<BlockPoolStateView<'static>> {
    fn from(wrapper: BlockPoolStateOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<BlockPoolStateView<'static>>>
for BlockPoolStateOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<BlockPoolStateView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::BlockPoolState {
    type View<'a> = BlockPoolStateView<'a>;
    type ViewHandle = BlockPoolStateOwnedView;
}
