// @generated
// This file is @generated by prost-build.
/// Both protocol outputs belong to the same complete block. V2 supplies closing
/// reserves; V3 supplies ordered changes requiring a verified starting state.
/// Neither output establishes pool authenticity or token/price interpretation.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockPoolState {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="2")]
    pub block_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub parent_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(int64, tag="4")]
    pub timestamp_seconds: i64,
    #[prost(int32, tag="5")]
    pub timestamp_nanos: i32,
    #[prost(message, repeated, tag="6")]
    pub v2_pools: ::prost::alloc::vec::Vec<super::super::super::uniswap::v2::PoolClose>,
    #[prost(message, repeated, tag="7")]
    pub v3_pools: ::prost::alloc::vec::Vec<super::super::super::uniswap::v3::PoolChanges>,
}
// @@protoc_insertion_point(module)
