// @generated by buffa-codegen. DO NOT EDIT.
// source: erc20_events.proto

/// Shape of the log relative to the ERC-20 ABI encoding.
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(i32)]
pub enum LogShape {
    LOG_SHAPE_UNSPECIFIED = 0i32,
    /// Three topics with canonically padded addresses and exactly 32 bytes of
    /// data: the ERC-20 encoding.
    LOG_SHAPE_ERC20 = 1i32,
    /// Four topics with padded addresses and no data: the ERC-721 encoding
    /// (`tokenId` indexed). Reported for the consumer's classification; the
    /// `amount`/`value` field then carries the token id, not a quantity.
    LOG_SHAPE_ERC721 = 2i32,
    /// Same topic0 but neither shape: nonstandard encodings are kept as facts
    /// with raw sizes and no decoded participants.
    LOG_SHAPE_NONSTANDARD = 3i32,
}
impl LogShape {
    ///Idiomatic alias for [`Self::LOG_SHAPE_UNSPECIFIED`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Unspecified: Self = Self::LOG_SHAPE_UNSPECIFIED;
    ///Idiomatic alias for [`Self::LOG_SHAPE_ERC20`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Erc20: Self = Self::LOG_SHAPE_ERC20;
    ///Idiomatic alias for [`Self::LOG_SHAPE_ERC721`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Erc721: Self = Self::LOG_SHAPE_ERC721;
    ///Idiomatic alias for [`Self::LOG_SHAPE_NONSTANDARD`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Nonstandard: Self = Self::LOG_SHAPE_NONSTANDARD;
}
impl ::core::default::Default for LogShape {
    fn default() -> Self {
        Self::LOG_SHAPE_UNSPECIFIED
    }
}
impl ::buffa::Enumeration for LogShape {
    fn from_i32(value: i32) -> ::core::option::Option<Self> {
        match value {
            0i32 => ::core::option::Option::Some(Self::LOG_SHAPE_UNSPECIFIED),
            1i32 => ::core::option::Option::Some(Self::LOG_SHAPE_ERC20),
            2i32 => ::core::option::Option::Some(Self::LOG_SHAPE_ERC721),
            3i32 => ::core::option::Option::Some(Self::LOG_SHAPE_NONSTANDARD),
            _ => ::core::option::Option::None,
        }
    }
    fn to_i32(&self) -> i32 {
        *self as i32
    }
    fn proto_name(&self) -> &'static str {
        match self {
            Self::LOG_SHAPE_UNSPECIFIED => "LOG_SHAPE_UNSPECIFIED",
            Self::LOG_SHAPE_ERC20 => "LOG_SHAPE_ERC20",
            Self::LOG_SHAPE_ERC721 => "LOG_SHAPE_ERC721",
            Self::LOG_SHAPE_NONSTANDARD => "LOG_SHAPE_NONSTANDARD",
        }
    }
    fn from_proto_name(name: &str) -> ::core::option::Option<Self> {
        match name {
            "LOG_SHAPE_UNSPECIFIED" => {
                ::core::option::Option::Some(Self::LOG_SHAPE_UNSPECIFIED)
            }
            "LOG_SHAPE_ERC20" => ::core::option::Option::Some(Self::LOG_SHAPE_ERC20),
            "LOG_SHAPE_ERC721" => ::core::option::Option::Some(Self::LOG_SHAPE_ERC721),
            "LOG_SHAPE_NONSTANDARD" => {
                ::core::option::Option::Some(Self::LOG_SHAPE_NONSTANDARD)
            }
            _ => ::core::option::Option::None,
        }
    }
    fn values() -> &'static [Self] {
        &[
            Self::LOG_SHAPE_UNSPECIFIED,
            Self::LOG_SHAPE_ERC20,
            Self::LOG_SHAPE_ERC721,
            Self::LOG_SHAPE_NONSTANDARD,
        ]
    }
}
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(i32)]
pub enum Scope {
    SCOPE_UNSPECIFIED = 0i32,
    SCOPE_TRANSACTION = 1i32,
    SCOPE_SYSTEM_CALL = 2i32,
}
impl Scope {
    ///Idiomatic alias for [`Self::SCOPE_UNSPECIFIED`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Unspecified: Self = Self::SCOPE_UNSPECIFIED;
    ///Idiomatic alias for [`Self::SCOPE_TRANSACTION`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Transaction: Self = Self::SCOPE_TRANSACTION;
    ///Idiomatic alias for [`Self::SCOPE_SYSTEM_CALL`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const SystemCall: Self = Self::SCOPE_SYSTEM_CALL;
}
impl ::core::default::Default for Scope {
    fn default() -> Self {
        Self::SCOPE_UNSPECIFIED
    }
}
impl ::buffa::Enumeration for Scope {
    fn from_i32(value: i32) -> ::core::option::Option<Self> {
        match value {
            0i32 => ::core::option::Option::Some(Self::SCOPE_UNSPECIFIED),
            1i32 => ::core::option::Option::Some(Self::SCOPE_TRANSACTION),
            2i32 => ::core::option::Option::Some(Self::SCOPE_SYSTEM_CALL),
            _ => ::core::option::Option::None,
        }
    }
    fn to_i32(&self) -> i32 {
        *self as i32
    }
    fn proto_name(&self) -> &'static str {
        match self {
            Self::SCOPE_UNSPECIFIED => "SCOPE_UNSPECIFIED",
            Self::SCOPE_TRANSACTION => "SCOPE_TRANSACTION",
            Self::SCOPE_SYSTEM_CALL => "SCOPE_SYSTEM_CALL",
        }
    }
    fn from_proto_name(name: &str) -> ::core::option::Option<Self> {
        match name {
            "SCOPE_UNSPECIFIED" => ::core::option::Option::Some(Self::SCOPE_UNSPECIFIED),
            "SCOPE_TRANSACTION" => ::core::option::Option::Some(Self::SCOPE_TRANSACTION),
            "SCOPE_SYSTEM_CALL" => ::core::option::Option::Some(Self::SCOPE_SYSTEM_CALL),
            _ => ::core::option::Option::None,
        }
    }
    fn values() -> &'static [Self] {
        &[Self::SCOPE_UNSPECIFIED, Self::SCOPE_TRANSACTION, Self::SCOPE_SYSTEM_CALL]
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct Events {
    /// Exactly one row per delivered block.
    ///
    /// Field 1: `clocks`
    pub clocks: ::buffa::alloc::vec::Vec<BlockClock>,
    /// Field 2: `transfers`
    pub transfers: ::buffa::alloc::vec::Vec<Transfer>,
    /// Field 3: `approvals`
    pub approvals: ::buffa::alloc::vec::Vec<Approval>,
}
impl ::core::fmt::Debug for Events {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Events")
            .field("clocks", &self.clocks)
            .field("transfers", &self.transfers)
            .field("approvals", &self.approvals)
            .finish()
    }
}
impl Events {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/erc20.events.v1.Events";
}
::buffa::impl_default_instance!(Events);
impl ::buffa::MessageName for Events {
    const PACKAGE: &'static str = "erc20.events.v1";
    const NAME: &'static str = "Events";
    const FULL_NAME: &'static str = "erc20.events.v1.Events";
    const TYPE_URL: &'static str = "type.googleapis.com/erc20.events.v1.Events";
}
impl ::buffa::Message for Events {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.clocks {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.transfers {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.approvals {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.clocks {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for v in &self.transfers {
            ::buffa::types::put_len_delimited_header(
                2u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for v in &self.approvals {
            ::buffa::types::put_len_delimited_header(
                3u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.clocks.push(elem);
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.transfers.push(elem);
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.approvals.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.clocks.clear();
        self.transfers.clear();
        self.approvals.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct BlockClock {
    /// Field 1: `chain_id`
    pub chain_id: u64,
    /// Field 2: `number`
    pub number: u64,
    /// Field 3: `hash`
    pub hash: ::buffa::alloc::vec::Vec<u8>,
    /// Field 4: `parent_hash`
    pub parent_hash: ::buffa::alloc::vec::Vec<u8>,
    /// Field 5: `timestamp`
    pub timestamp: u64,
    /// Field 6: `state_root`
    pub state_root: ::buffa::alloc::vec::Vec<u8>,
    /// Field 7: `producer_version`
    pub producer_version: u32,
    /// Field 8: `spec_revision`
    pub spec_revision: u32,
    /// Field 9: `package`
    pub package: ::buffa::alloc::string::String,
    /// Field 10: `package_version`
    pub package_version: ::buffa::alloc::string::String,
    /// Field 11: `parameters_sha256`
    pub parameters_sha256: ::buffa::alloc::string::String,
    /// Field 12: `transfer_count`
    pub transfer_count: u32,
    /// Field 13: `approval_count`
    pub approval_count: u32,
}
impl ::core::fmt::Debug for BlockClock {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("BlockClock")
            .field("chain_id", &self.chain_id)
            .field("number", &self.number)
            .field("hash", &self.hash)
            .field("parent_hash", &self.parent_hash)
            .field("timestamp", &self.timestamp)
            .field("state_root", &self.state_root)
            .field("producer_version", &self.producer_version)
            .field("spec_revision", &self.spec_revision)
            .field("package", &self.package)
            .field("package_version", &self.package_version)
            .field("parameters_sha256", &self.parameters_sha256)
            .field("transfer_count", &self.transfer_count)
            .field("approval_count", &self.approval_count)
            .finish()
    }
}
impl BlockClock {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/erc20.events.v1.BlockClock";
}
::buffa::impl_default_instance!(BlockClock);
impl ::buffa::MessageName for BlockClock {
    const PACKAGE: &'static str = "erc20.events.v1";
    const NAME: &'static str = "BlockClock";
    const FULL_NAME: &'static str = "erc20.events.v1.BlockClock";
    const TYPE_URL: &'static str = "type.googleapis.com/erc20.events.v1.BlockClock";
}
impl ::buffa::Message for BlockClock {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.chain_id != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.chain_id) as u64;
        }
        if self.number != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.number) as u64;
        }
        if !self.hash.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.hash) as u64;
        }
        if !self.parent_hash.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.parent_hash) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        if !self.state_root.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.state_root) as u64;
        }
        if self.producer_version != 0u32 {
            size
                += 1u64
                    + ::buffa::types::uint32_encoded_len(self.producer_version) as u64;
        }
        if self.spec_revision != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.spec_revision) as u64;
        }
        if !self.package.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.package) as u64;
        }
        if !self.package_version.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.package_version) as u64;
        }
        if !self.parameters_sha256.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.parameters_sha256) as u64;
        }
        if self.transfer_count != 0u32 {
            size
                += 1u64 + ::buffa::types::uint32_encoded_len(self.transfer_count) as u64;
        }
        if self.approval_count != 0u32 {
            size
                += 1u64 + ::buffa::types::uint32_encoded_len(self.approval_count) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.chain_id != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.chain_id, buf);
        }
        if self.number != 0u64 {
            ::buffa::types::put_uint64_field(2u32, self.number, buf);
        }
        if !self.hash.is_empty() {
            ::buffa::types::put_shared_bytes_field(3u32, &self.hash, buf);
        }
        if !self.parent_hash.is_empty() {
            ::buffa::types::put_shared_bytes_field(4u32, &self.parent_hash, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(5u32, self.timestamp, buf);
        }
        if !self.state_root.is_empty() {
            ::buffa::types::put_shared_bytes_field(6u32, &self.state_root, buf);
        }
        if self.producer_version != 0u32 {
            ::buffa::types::put_uint32_field(7u32, self.producer_version, buf);
        }
        if self.spec_revision != 0u32 {
            ::buffa::types::put_uint32_field(8u32, self.spec_revision, buf);
        }
        if !self.package.is_empty() {
            ::buffa::types::put_string_field(9u32, &self.package, buf);
        }
        if !self.package_version.is_empty() {
            ::buffa::types::put_string_field(10u32, &self.package_version, buf);
        }
        if !self.parameters_sha256.is_empty() {
            ::buffa::types::put_string_field(11u32, &self.parameters_sha256, buf);
        }
        if self.transfer_count != 0u32 {
            ::buffa::types::put_uint32_field(12u32, self.transfer_count, buf);
        }
        if self.approval_count != 0u32 {
            ::buffa::types::put_uint32_field(13u32, self.approval_count, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.chain_id = ::buffa::types::decode_uint64(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.number = ::buffa::types::decode_uint64(buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.hash, buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.parent_hash, buf)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.timestamp = ::buffa::types::decode_uint64(buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.state_root, buf)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.producer_version = ::buffa::types::decode_uint32(buf)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.spec_revision = ::buffa::types::decode_uint32(buf)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.package, buf)?;
            }
            10u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.package_version, buf)?;
            }
            11u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.parameters_sha256, buf)?;
            }
            12u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.transfer_count = ::buffa::types::decode_uint32(buf)?;
            }
            13u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.approval_count = ::buffa::types::decode_uint32(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.chain_id = 0u64;
        self.number = 0u64;
        self.hash.clear();
        self.parent_hash.clear();
        self.timestamp = 0u64;
        self.state_root.clear();
        self.producer_version = 0u32;
        self.spec_revision = 0u32;
        self.package.clear();
        self.package_version.clear();
        self.parameters_sha256.clear();
        self.transfer_count = 0u32;
        self.approval_count = 0u32;
    }
}
/// One `Transfer(address,address,uint256)`-signed log.
/// Identity: (scope, transaction_hash, ordinal). Sort: (scope,
/// transaction_index, ordinal, call_index, log_index).
#[derive(Clone, PartialEq, Default)]
pub struct Transfer {
    /// Field 1: `chain_id`
    pub chain_id: u64,
    /// Field 2: `scope`
    pub scope: ::buffa::EnumValue<Scope>,
    /// Field 3: `transaction_hash`
    pub transaction_hash: ::buffa::alloc::vec::Vec<u8>,
    /// Field 4: `transaction_index`
    pub transaction_index: u32,
    /// Field 5: `call_index`
    pub call_index: u32,
    /// Producer log index within the transaction; only persisted logs are
    /// receipt logs.
    ///
    /// Field 6: `log_index`
    pub log_index: u32,
    /// Index within the block's persisted logs; 0 for attempts.
    ///
    /// Field 7: `block_index`
    pub block_index: u32,
    /// Field 8: `ordinal`
    pub ordinal: u64,
    /// Emitting contract.
    ///
    /// Field 9: `token`
    pub token: ::buffa::alloc::vec::Vec<u8>,
    /// Field 10: `shape`
    pub shape: ::buffa::EnumValue<LogShape>,
    /// Decoded only for ERC20 and ERC721 shapes; empty otherwise.
    ///
    /// Field 11: `from`
    pub from: ::buffa::alloc::vec::Vec<u8>,
    /// Field 12: `to`
    pub to: ::buffa::alloc::vec::Vec<u8>,
    /// ERC20: the raw integer amount. ERC721: the token id. Empty for nonstandard.
    ///
    /// Field 13: `amount`
    pub amount: ::buffa::alloc::string::String,
    /// Field 14: `topic_count`
    pub topic_count: u32,
    /// Field 15: `data_size`
    pub data_size: u32,
    /// Convenience facts, never labels: `from` is the zero address; `to` is the
    /// zero address; `from == to`.
    ///
    /// Field 16: `from_zero`
    pub from_zero: bool,
    /// Field 17: `to_zero`
    pub to_zero: bool,
    /// Field 18: `self_transfer`
    pub self_transfer: bool,
    /// The log survived: succeeded transaction and non-reverted frame, or a
    /// non-reverted system call.
    ///
    /// Field 19: `persisted`
    pub persisted: bool,
}
impl ::core::fmt::Debug for Transfer {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Transfer")
            .field("chain_id", &self.chain_id)
            .field("scope", &self.scope)
            .field("transaction_hash", &self.transaction_hash)
            .field("transaction_index", &self.transaction_index)
            .field("call_index", &self.call_index)
            .field("log_index", &self.log_index)
            .field("block_index", &self.block_index)
            .field("ordinal", &self.ordinal)
            .field("token", &self.token)
            .field("shape", &self.shape)
            .field("from", &self.from)
            .field("to", &self.to)
            .field("amount", &self.amount)
            .field("topic_count", &self.topic_count)
            .field("data_size", &self.data_size)
            .field("from_zero", &self.from_zero)
            .field("to_zero", &self.to_zero)
            .field("self_transfer", &self.self_transfer)
            .field("persisted", &self.persisted)
            .finish()
    }
}
impl Transfer {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/erc20.events.v1.Transfer";
}
::buffa::impl_default_instance!(Transfer);
impl ::buffa::MessageName for Transfer {
    const PACKAGE: &'static str = "erc20.events.v1";
    const NAME: &'static str = "Transfer";
    const FULL_NAME: &'static str = "erc20.events.v1.Transfer";
    const TYPE_URL: &'static str = "type.googleapis.com/erc20.events.v1.Transfer";
}
impl ::buffa::Message for Transfer {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.chain_id != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.chain_id) as u64;
        }
        {
            let val = self.scope.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        if !self.transaction_hash.is_empty() {
            size
                += 1u64
                    + ::buffa::types::bytes_encoded_len(&self.transaction_hash) as u64;
        }
        if self.transaction_index != 0u32 {
            size
                += 1u64
                    + ::buffa::types::uint32_encoded_len(self.transaction_index) as u64;
        }
        if self.call_index != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.call_index) as u64;
        }
        if self.log_index != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.log_index) as u64;
        }
        if self.block_index != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.block_index) as u64;
        }
        if self.ordinal != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.ordinal) as u64;
        }
        if !self.token.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.token) as u64;
        }
        {
            let val = self.shape.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        if !self.from.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.from) as u64;
        }
        if !self.to.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.to) as u64;
        }
        if !self.amount.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.amount) as u64;
        }
        if self.topic_count != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.topic_count) as u64;
        }
        if self.data_size != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.data_size) as u64;
        }
        if self.from_zero {
            size += 2u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        if self.to_zero {
            size += 2u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        if self.self_transfer {
            size += 2u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        if self.persisted {
            size += 2u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.chain_id != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.chain_id, buf);
        }
        {
            let val = self.scope.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(2u32, val, buf);
            }
        }
        if !self.transaction_hash.is_empty() {
            ::buffa::types::put_shared_bytes_field(3u32, &self.transaction_hash, buf);
        }
        if self.transaction_index != 0u32 {
            ::buffa::types::put_uint32_field(4u32, self.transaction_index, buf);
        }
        if self.call_index != 0u32 {
            ::buffa::types::put_uint32_field(5u32, self.call_index, buf);
        }
        if self.log_index != 0u32 {
            ::buffa::types::put_uint32_field(6u32, self.log_index, buf);
        }
        if self.block_index != 0u32 {
            ::buffa::types::put_uint32_field(7u32, self.block_index, buf);
        }
        if self.ordinal != 0u64 {
            ::buffa::types::put_uint64_field(8u32, self.ordinal, buf);
        }
        if !self.token.is_empty() {
            ::buffa::types::put_shared_bytes_field(9u32, &self.token, buf);
        }
        {
            let val = self.shape.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(10u32, val, buf);
            }
        }
        if !self.from.is_empty() {
            ::buffa::types::put_shared_bytes_field(11u32, &self.from, buf);
        }
        if !self.to.is_empty() {
            ::buffa::types::put_shared_bytes_field(12u32, &self.to, buf);
        }
        if !self.amount.is_empty() {
            ::buffa::types::put_string_field(13u32, &self.amount, buf);
        }
        if self.topic_count != 0u32 {
            ::buffa::types::put_uint32_field(14u32, self.topic_count, buf);
        }
        if self.data_size != 0u32 {
            ::buffa::types::put_uint32_field(15u32, self.data_size, buf);
        }
        if self.from_zero {
            ::buffa::types::put_bool_field(16u32, self.from_zero, buf);
        }
        if self.to_zero {
            ::buffa::types::put_bool_field(17u32, self.to_zero, buf);
        }
        if self.self_transfer {
            ::buffa::types::put_bool_field(18u32, self.self_transfer, buf);
        }
        if self.persisted {
            ::buffa::types::put_bool_field(19u32, self.persisted, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.chain_id = ::buffa::types::decode_uint64(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.scope = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.transaction_hash, buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.transaction_index = ::buffa::types::decode_uint32(buf)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.call_index = ::buffa::types::decode_uint32(buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.log_index = ::buffa::types::decode_uint32(buf)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.block_index = ::buffa::types::decode_uint32(buf)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.ordinal = ::buffa::types::decode_uint64(buf)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.token, buf)?;
            }
            10u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.shape = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            11u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.from, buf)?;
            }
            12u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.to, buf)?;
            }
            13u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.amount, buf)?;
            }
            14u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.topic_count = ::buffa::types::decode_uint32(buf)?;
            }
            15u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.data_size = ::buffa::types::decode_uint32(buf)?;
            }
            16u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.from_zero = ::buffa::types::decode_bool(buf)?;
            }
            17u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.to_zero = ::buffa::types::decode_bool(buf)?;
            }
            18u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.self_transfer = ::buffa::types::decode_bool(buf)?;
            }
            19u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.persisted = ::buffa::types::decode_bool(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.chain_id = 0u64;
        self.scope = ::buffa::EnumValue::from(0);
        self.transaction_hash.clear();
        self.transaction_index = 0u32;
        self.call_index = 0u32;
        self.log_index = 0u32;
        self.block_index = 0u32;
        self.ordinal = 0u64;
        self.token.clear();
        self.shape = ::buffa::EnumValue::from(0);
        self.from.clear();
        self.to.clear();
        self.amount.clear();
        self.topic_count = 0u32;
        self.data_size = 0u32;
        self.from_zero = false;
        self.to_zero = false;
        self.self_transfer = false;
        self.persisted = false;
    }
}
/// One `Approval(address,address,uint256)`-signed log.
/// Identity and sort as Transfer.
#[derive(Clone, PartialEq, Default)]
pub struct Approval {
    /// Field 1: `chain_id`
    pub chain_id: u64,
    /// Field 2: `scope`
    pub scope: ::buffa::EnumValue<Scope>,
    /// Field 3: `transaction_hash`
    pub transaction_hash: ::buffa::alloc::vec::Vec<u8>,
    /// Field 4: `transaction_index`
    pub transaction_index: u32,
    /// Field 5: `call_index`
    pub call_index: u32,
    /// Field 6: `log_index`
    pub log_index: u32,
    /// Field 7: `block_index`
    pub block_index: u32,
    /// Field 8: `ordinal`
    pub ordinal: u64,
    /// Field 9: `token`
    pub token: ::buffa::alloc::vec::Vec<u8>,
    /// Field 10: `shape`
    pub shape: ::buffa::EnumValue<LogShape>,
    /// Field 11: `owner`
    pub owner: ::buffa::alloc::vec::Vec<u8>,
    /// Field 12: `spender`
    pub spender: ::buffa::alloc::vec::Vec<u8>,
    /// ERC20: the approved value. ERC721: the token id. Empty for nonstandard.
    ///
    /// Field 13: `value`
    pub value: ::buffa::alloc::string::String,
    /// Field 14: `topic_count`
    pub topic_count: u32,
    /// Field 15: `data_size`
    pub data_size: u32,
    /// `value` is 2^256-1.
    ///
    /// Field 16: `unlimited`
    pub unlimited: bool,
    /// `value` is zero (a revocation-shaped event).
    ///
    /// Field 17: `zero_value`
    pub zero_value: bool,
    /// Field 18: `persisted`
    pub persisted: bool,
}
impl ::core::fmt::Debug for Approval {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Approval")
            .field("chain_id", &self.chain_id)
            .field("scope", &self.scope)
            .field("transaction_hash", &self.transaction_hash)
            .field("transaction_index", &self.transaction_index)
            .field("call_index", &self.call_index)
            .field("log_index", &self.log_index)
            .field("block_index", &self.block_index)
            .field("ordinal", &self.ordinal)
            .field("token", &self.token)
            .field("shape", &self.shape)
            .field("owner", &self.owner)
            .field("spender", &self.spender)
            .field("value", &self.value)
            .field("topic_count", &self.topic_count)
            .field("data_size", &self.data_size)
            .field("unlimited", &self.unlimited)
            .field("zero_value", &self.zero_value)
            .field("persisted", &self.persisted)
            .finish()
    }
}
impl Approval {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/erc20.events.v1.Approval";
}
::buffa::impl_default_instance!(Approval);
impl ::buffa::MessageName for Approval {
    const PACKAGE: &'static str = "erc20.events.v1";
    const NAME: &'static str = "Approval";
    const FULL_NAME: &'static str = "erc20.events.v1.Approval";
    const TYPE_URL: &'static str = "type.googleapis.com/erc20.events.v1.Approval";
}
impl ::buffa::Message for Approval {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.chain_id != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.chain_id) as u64;
        }
        {
            let val = self.scope.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        if !self.transaction_hash.is_empty() {
            size
                += 1u64
                    + ::buffa::types::bytes_encoded_len(&self.transaction_hash) as u64;
        }
        if self.transaction_index != 0u32 {
            size
                += 1u64
                    + ::buffa::types::uint32_encoded_len(self.transaction_index) as u64;
        }
        if self.call_index != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.call_index) as u64;
        }
        if self.log_index != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.log_index) as u64;
        }
        if self.block_index != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.block_index) as u64;
        }
        if self.ordinal != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.ordinal) as u64;
        }
        if !self.token.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.token) as u64;
        }
        {
            let val = self.shape.to_i32();
            if val != 0 {
                size += 1u64 + ::buffa::types::int32_encoded_len(val) as u64;
            }
        }
        if !self.owner.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.owner) as u64;
        }
        if !self.spender.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.spender) as u64;
        }
        if !self.value.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.value) as u64;
        }
        if self.topic_count != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.topic_count) as u64;
        }
        if self.data_size != 0u32 {
            size += 1u64 + ::buffa::types::uint32_encoded_len(self.data_size) as u64;
        }
        if self.unlimited {
            size += 2u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        if self.zero_value {
            size += 2u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        if self.persisted {
            size += 2u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.chain_id != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.chain_id, buf);
        }
        {
            let val = self.scope.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(2u32, val, buf);
            }
        }
        if !self.transaction_hash.is_empty() {
            ::buffa::types::put_shared_bytes_field(3u32, &self.transaction_hash, buf);
        }
        if self.transaction_index != 0u32 {
            ::buffa::types::put_uint32_field(4u32, self.transaction_index, buf);
        }
        if self.call_index != 0u32 {
            ::buffa::types::put_uint32_field(5u32, self.call_index, buf);
        }
        if self.log_index != 0u32 {
            ::buffa::types::put_uint32_field(6u32, self.log_index, buf);
        }
        if self.block_index != 0u32 {
            ::buffa::types::put_uint32_field(7u32, self.block_index, buf);
        }
        if self.ordinal != 0u64 {
            ::buffa::types::put_uint64_field(8u32, self.ordinal, buf);
        }
        if !self.token.is_empty() {
            ::buffa::types::put_shared_bytes_field(9u32, &self.token, buf);
        }
        {
            let val = self.shape.to_i32();
            if val != 0 {
                ::buffa::types::put_int32_field(10u32, val, buf);
            }
        }
        if !self.owner.is_empty() {
            ::buffa::types::put_shared_bytes_field(11u32, &self.owner, buf);
        }
        if !self.spender.is_empty() {
            ::buffa::types::put_shared_bytes_field(12u32, &self.spender, buf);
        }
        if !self.value.is_empty() {
            ::buffa::types::put_string_field(13u32, &self.value, buf);
        }
        if self.topic_count != 0u32 {
            ::buffa::types::put_uint32_field(14u32, self.topic_count, buf);
        }
        if self.data_size != 0u32 {
            ::buffa::types::put_uint32_field(15u32, self.data_size, buf);
        }
        if self.unlimited {
            ::buffa::types::put_bool_field(16u32, self.unlimited, buf);
        }
        if self.zero_value {
            ::buffa::types::put_bool_field(17u32, self.zero_value, buf);
        }
        if self.persisted {
            ::buffa::types::put_bool_field(18u32, self.persisted, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.chain_id = ::buffa::types::decode_uint64(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.scope = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.transaction_hash, buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.transaction_index = ::buffa::types::decode_uint32(buf)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.call_index = ::buffa::types::decode_uint32(buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.log_index = ::buffa::types::decode_uint32(buf)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.block_index = ::buffa::types::decode_uint32(buf)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.ordinal = ::buffa::types::decode_uint64(buf)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.token, buf)?;
            }
            10u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.shape = ::buffa::EnumValue::from(
                    ::buffa::types::decode_int32(buf)?,
                );
            }
            11u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.owner, buf)?;
            }
            12u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.spender, buf)?;
            }
            13u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.value, buf)?;
            }
            14u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.topic_count = ::buffa::types::decode_uint32(buf)?;
            }
            15u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.data_size = ::buffa::types::decode_uint32(buf)?;
            }
            16u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.unlimited = ::buffa::types::decode_bool(buf)?;
            }
            17u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.zero_value = ::buffa::types::decode_bool(buf)?;
            }
            18u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.persisted = ::buffa::types::decode_bool(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.chain_id = 0u64;
        self.scope = ::buffa::EnumValue::from(0);
        self.transaction_hash.clear();
        self.transaction_index = 0u32;
        self.call_index = 0u32;
        self.log_index = 0u32;
        self.block_index = 0u32;
        self.ordinal = 0u64;
        self.token.clear();
        self.shape = ::buffa::EnumValue::from(0);
        self.owner.clear();
        self.spender.clear();
        self.value.clear();
        self.topic_count = 0u32;
        self.data_size = 0u32;
        self.unlimited = false;
        self.zero_value = false;
        self.persisted = false;
    }
}
