// @generated
// This file is @generated by prost-build.
/// One `Events` per delivered block. Order inside each list is deterministic
/// (sort keys are given per message) because the sink's `_row_id_` is the
/// element index.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    /// Exactly one row per delivered block, including blocks without any other
    /// row, so the clock is explicit rather than inferred from nonempty output.
    #[prost(message, repeated, tag="1")]
    pub clocks: ::prost::alloc::vec::Vec<BlockClock>,
    /// Model epoch lifecycle: BOUND, REAFFIRMED, INVALIDATED, SUSPENDED.
    #[prost(message, repeated, tag="2")]
    pub epochs: ::prost::alloc::vec::Vec<ModelEpoch>,
    /// Dependency edges of a BOUND or REAFFIRMED epoch.
    #[prost(message, repeated, tag="3")]
    pub dependencies: ::prost::alloc::vec::Vec<Dependency>,
    /// Same-balance identity aliases (Arc native USDC and its ERC-20 view).
    #[prost(message, repeated, tag="4")]
    pub aliases: ::prost::alloc::vec::Vec<AssetAlias>,
    /// Holder basis facts: scaled balances, shares, signed principal.
    #[prost(message, repeated, tag="5")]
    pub holder_basis: ::prost::alloc::vec::Vec<HolderBasis>,
    /// Shared global state facts: indices, rates, clocks, totals, constants,
    /// cross-contract inputs.
    #[prost(message, repeated, tag="6")]
    pub global_state: ::prost::alloc::vec::Vec<GlobalState>,
}
// ---------------------------------------------------------------------------
// Rows
// ---------------------------------------------------------------------------

/// Exactly one per delivered block, including blocks with no other rows, so
/// time- and height-dependent evaluation has a canonical clock for every
/// height and the sink's block markers list every delivered block for this
/// package. It is a clock fact, not a publication manifest: sink writes are
/// not multi-table transactions; the `*_count` fields let a consumer check
/// that every row of the block landed.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockClock {
    /// Caller-qualified chain id echoed from parameters; the block carries none
    /// and the manifest binds the network.
    #[prost(uint64, tag="1")]
    pub chain_id: u64,
    #[prost(uint64, tag="2")]
    pub number: u64,
    /// 32 bytes.
    #[prost(bytes="vec", tag="3")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    /// 32 bytes.
    #[prost(bytes="vec", tag="4")]
    pub parent_hash: ::prost::alloc::vec::Vec<u8>,
    /// Header timestamp, seconds. Not strictly increasing on every chain.
    #[prost(uint64, tag="5")]
    pub timestamp: u64,
    /// 32 bytes; binds the row to the canonical header.
    #[prost(bytes="vec", tag="6")]
    pub state_root: ::prost::alloc::vec::Vec<u8>,
    /// `sf.ethereum.type.v2.Block.ver`; the package accepts 4 and 5 only.
    #[prost(uint32, tag="7")]
    pub producer_version: u32,
    /// Semantic revision of this package's emission rules; increments when a
    /// new enum value, table or rule is introduced. Wire compatibility is
    /// unaffected.
    #[prost(uint32, tag="8")]
    pub spec_revision: u32,
    /// Producing package name and version, e.g. "aave_balance_state", "v0.1.0".
    #[prost(string, tag="9")]
    pub package: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub package_version: ::prost::alloc::string::String,
    /// SHA-256 of the exact `map_events` parameters, hex without prefix.
    #[prost(string, tag="11")]
    pub parameters_sha256: ::prost::alloc::string::String,
    /// Row counts of this block in the other tables.
    #[prost(uint32, tag="12")]
    pub epoch_count: u32,
    #[prost(uint32, tag="13")]
    pub dependency_count: u32,
    #[prost(uint32, tag="14")]
    pub alias_count: u32,
    #[prost(uint32, tag="15")]
    pub holder_basis_count: u32,
    #[prost(uint32, tag="16")]
    pub global_state_count: u32,
}
/// Model epoch lifecycle for one market.
/// Sort: (market, epoch, ordinal, kind).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelEpoch {
    #[prost(uint64, tag="1")]
    pub chain_id: u64,
    /// Token or market whose holder basis this epoch decodes (aToken proxy,
    /// cToken, Comet proxy, stETH proxy, vault).
    #[prost(bytes="vec", tag="2")]
    pub market: ::prost::alloc::vec::Vec<u8>,
    /// Caller-assigned sequence per (chain, market), starting at 1, strictly
    /// increasing with activation. Holder and global rows join on it.
    #[prost(uint32, tag="3")]
    pub epoch: u32,
    #[prost(enumeration="EpochEventKind", tag="4")]
    pub kind: i32,
    #[prost(enumeration="ModelFamily", tag="5")]
    pub family: i32,
    /// Stable formula identifier, e.g. "aave-v3/atoken/scaled-floor",
    /// "aave-v3/atoken/scaled-half-up", "compound-v2/ctoken/exchange-rate",
    /// "comet/base-supply-index", "lido/steth/shares-v4",
    /// "erc4626/static-atoken-lm/normalized-income", "erc4626/sdai/pot-rpow".
    #[prost(string, tag="6")]
    pub model_id: ::prost::alloc::string::String,
    /// Source revision the model follows, e.g.
    /// "aave-dao/aave-v3-origin@8305565ae342f1773c42cd2e4593f175fe5968a0".
    #[prost(string, tag="7")]
    pub source_pin: ::prost::alloc::string::String,
    /// Protocol-declared revision (Aave ATOKEN_REVISION "5", Lido contract
    /// version "4"); "" when none.
    #[prost(string, tag="8")]
    pub implementation_revision: ::prost::alloc::string::String,
    #[prost(enumeration="BasisKind", tag="9")]
    pub basis_kind: i32,
    /// Denominator constant of the basis -> balance conversion as a decimal
    /// ("1000000000000000000000000000" for ray, "1000000000000000" for Comet,
    /// "" for share ratios).
    #[prost(string, tag="10")]
    pub basis_scale: ::prost::alloc::string::String,
    /// Rounding of the basis -> observable balance conversion.
    #[prost(enumeration="Rounding", tag="11")]
    pub balance_rounding: i32,
    /// Bit range of the holder word that holds the basis (Aave 0/120 since
    /// v3.4, 0/128 before; Comet 0/104 signed; plain words 0/256).
    #[prost(uint32, tag="12")]
    pub basis_bit_offset: u32,
    #[prost(uint32, tag="13")]
    pub basis_bit_width: u32,
    #[prost(bool, tag="14")]
    pub basis_signed: bool,
    /// Identity bound for this epoch.
    #[prost(bytes="vec", tag="15")]
    pub market_code_hash: ::prost::alloc::vec::Vec<u8>,
    /// "" when `market` is not a proxy.
    #[prost(bytes="vec", tag="16")]
    pub implementation: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="17")]
    pub implementation_code_hash: ::prost::alloc::vec::Vec<u8>,
    /// Pointer slot on `market`; "" when none.
    #[prost(bytes="vec", tag="18")]
    pub implementation_slot: ::prost::alloc::vec::Vec<u8>,
    /// First block (inclusive) and ordinal at which the epoch applies. Writes in
    /// the activation block with a smaller ordinal belong to the previous epoch.
    #[prost(uint64, tag="19")]
    pub activation_block: u64,
    #[prost(uint64, tag="20")]
    pub activation_ordinal: u64,
    /// Asset the evaluated balance is denominated in and its decimals: the
    /// underlying for aToken/cToken/vault, the base token for Comet, the market
    /// itself for stETH.
    #[prost(bytes="vec", tag="21")]
    pub balance_asset: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="22")]
    pub balance_decimals: u32,
    /// BOUND rows: true when holder basis words retained under the previous
    /// epoch stay evaluable under this one (same slot, bit range and meaning),
    /// e.g. Aave aToken revision 4 -> 5 where only rounding changed.
    #[prost(bool, tag="23")]
    pub basis_carryover: bool,
    /// Same statement for retained GlobalState rows; false at a storage
    /// migration or rate-model replacement.
    #[prost(bool, tag="24")]
    pub global_carryover: bool,
    /// INVALIDATED / SUSPENDED rows: why, and the persisted evidence in this
    /// block, verified by the map.
    #[prost(enumeration="InvalidationReason", tag="25")]
    pub reason: i32,
    #[prost(enumeration="Scope", tag="26")]
    pub scope: i32,
    #[prost(uint64, tag="27")]
    pub ordinal: u64,
    #[prost(uint32, tag="28")]
    pub transaction_index: u32,
    #[prost(bytes="vec", tag="29")]
    pub transaction_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="30")]
    pub call_index: u32,
    /// Contract written or whose code changed.
    #[prost(bytes="vec", tag="31")]
    pub evidence_contract: ::prost::alloc::vec::Vec<u8>,
    /// Pointer or version slot; "" for a code change.
    #[prost(bytes="vec", tag="32")]
    pub evidence_slot: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="33")]
    pub evidence_previous_word: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="34")]
    pub evidence_word: ::prost::alloc::vec::Vec<u8>,
    /// New runtime code hash on a code change.
    #[prost(bytes="vec", tag="35")]
    pub evidence_code_hash: ::prost::alloc::vec::Vec<u8>,
}
/// One dependency edge of a bound epoch, emitted with every BOUND and
/// REAFFIRMED ModelEpoch. The evaluation graph is recovered by following
/// `parent` from `market`.
/// Sort: (market, epoch, depth, role, contract).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dependency {
    #[prost(uint64, tag="1")]
    pub chain_id: u64,
    #[prost(bytes="vec", tag="2")]
    pub market: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="3")]
    pub epoch: u32,
    /// BOUND or REAFFIRMED.
    #[prost(enumeration="EpochEventKind", tag="4")]
    pub kind: i32,
    #[prost(enumeration="DependencyRole", tag="5")]
    pub role: i32,
    #[prost(bytes="vec", tag="6")]
    pub contract: ::prost::alloc::vec::Vec<u8>,
    /// "" for a direct dependency of `market`; otherwise the `contract` of the
    /// edge this one hangs from (token -> pool -> rate model).
    #[prost(bytes="vec", tag="7")]
    pub parent: ::prost::alloc::vec::Vec<u8>,
    /// 1 for direct edges.
    #[prost(uint32, tag="8")]
    pub depth: u32,
    #[prost(enumeration="BindingKind", tag="9")]
    pub binding: i32,
    /// Pinned runtime code hash; "" when not pinned.
    #[prost(bytes="vec", tag="10")]
    pub code_hash: ::prost::alloc::vec::Vec<u8>,
    /// STORAGE_POINTER: contract holding the slot, the slot, the expected word.
    #[prost(bytes="vec", tag="11")]
    pub pointer_contract: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="12")]
    pub pointer_slot: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="13")]
    pub pointer_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="14")]
    pub activation_block: u64,
    /// Where the identity was read (registry@commit).
    #[prost(string, tag="15")]
    pub source_pin: ::prost::alloc::string::String,
}
/// Same-balance alias declaration, emitted with BOUND/REAFFIRMED cadence by the
/// package that owns the alias. No holder rows are synthesized for the alias
/// side; consumers evaluate the alias view from the primary side's rows
/// (`native/balances` for Arc) with the scales below. Rows sharing
/// (asset, alias_of) are views of ONE balance and must never be summed.
/// Sort: (asset, alias_of).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AssetAlias {
    #[prost(uint64, tag="1")]
    pub chain_id: u64,
    #[prost(enumeration="AliasKind", tag="2")]
    pub kind: i32,
    /// BOUND or REAFFIRMED.
    #[prost(enumeration="EpochEventKind", tag="3")]
    pub event_kind: i32,
    /// The alias side (Arc: ERC-20 interface 0x3600...0000).
    #[prost(bytes="vec", tag="4")]
    pub asset: ::prost::alloc::vec::Vec<u8>,
    /// The primary, full-precision side; "" = the chain's native asset.
    #[prost(bytes="vec", tag="5")]
    pub alias_of: ::prost::alloc::vec::Vec<u8>,
    /// 10^decimals of each side as decimals ("1000000", "1000000000000000000").
    #[prost(string, tag="6")]
    pub asset_scale: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub alias_of_scale: ::prost::alloc::string::String,
    /// Rounding of alias_of -> asset (Arc: FLOOR; sub-unit amounts exist only on
    /// the primary side).
    #[prost(enumeration="Rounding", tag="8")]
    pub asset_rounding: i32,
    /// Emitter of ERC-20-style Transfer logs for primary-side movements (Arc:
    /// the system address 0xffff...fffe); "" when none. Recorded so transfer
    /// evidence is attributed once.
    #[prost(bytes="vec", tag="9")]
    pub log_emitter: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="10")]
    pub activation_block: u64,
    #[prost(string, tag="11")]
    pub source_pin: ::prost::alloc::string::String,
}
/// Holder basis fact.
/// Sort: (market, holder, ordinal, boundary).
///
/// A row is emitted only for a holder whose basis word was written in this
/// block. A holder without a row is missing/uninitialized; "0" is a known
/// zero. A shared index update (GlobalState) changes every initialized
/// holder's `balanceOf` without any holder row: consumers retain the last
/// basis per (market, holder) and the last global state per (market, field,
/// key), and evaluate at a selected canonical block with that block's
/// BlockClock and the epoch's formula.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HolderBasis {
    #[prost(uint64, tag="1")]
    pub chain_id: u64,
    #[prost(bytes="vec", tag="2")]
    pub market: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub holder: ::prost::alloc::vec::Vec<u8>,
    /// Joins ModelEpoch / Dependency.
    #[prost(uint32, tag="4")]
    pub epoch: u32,
    #[prost(enumeration="BasisKind", tag="5")]
    pub basis_kind: i32,
    /// Exact decimal integer. Negative only for SIGNED_PRINCIPAL.
    #[prost(string, tag="6")]
    pub value: ::prost::alloc::string::String,
    /// Decoded value before the first reduced write; "" when no prior word
    /// exists in the observation.
    #[prost(string, tag="7")]
    pub previous_value: ::prost::alloc::string::String,
    #[prost(enumeration="Observation", tag="8")]
    pub observation: i32,
    #[prost(enumeration="Boundary", tag="9")]
    pub boundary: i32,
    #[prost(enumeration="Scope", tag="10")]
    pub scope: i32,
    /// Last reduced write, execution ordinal (producer versions 4 and 5 only).
    #[prost(uint64, tag="11")]
    pub ordinal: u64,
    #[prost(uint64, tag="12")]
    pub first_ordinal: u64,
    /// Writes reduced into this row.
    #[prost(uint32, tag="13")]
    pub change_count: u32,
    #[prost(uint32, tag="14")]
    pub transaction_index: u32,
    /// "" outside TRANSACTION scope.
    #[prost(bytes="vec", tag="15")]
    pub transaction_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="16")]
    pub call_index: u32,
    /// Provenance of the word: contract whose storage holds it (== market unless
    /// delegated), 32-byte slot, raw words as persisted before the first and
    /// after the last write, and the decoded bit range.
    #[prost(bytes="vec", tag="17")]
    pub storage_contract: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="18")]
    pub storage_slot: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="19")]
    pub raw_previous_word: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="20")]
    pub raw_word: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="21")]
    pub bit_offset: u32,
    #[prost(uint32, tag="22")]
    pub bit_width: u32,
    /// Two's complement within [bit_offset, bit_offset + bit_width).
    #[prost(bool, tag="23")]
    pub signed: bool,
}
/// Shared global state fact consumed by `market`'s bound model.
/// Sort: (market, field, key, ordinal, boundary).
///
/// One row states ONE field. One persisted write to a packed slot yields one
/// row per decoded field (same slot and raw words, different bit ranges). A
/// set of rows for a market in one block is whatever that block wrote, never a
/// market snapshot: a consumer carries forward each field's own last
/// observation and treats an empty `value` as not carried. When two markets
/// consume the same write (sDAI and cDAI both read Pot.chi) one row per market
/// is emitted; `storage_contract` and `storage_slot` identify the single fact.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GlobalState {
    #[prost(uint64, tag="1")]
    pub chain_id: u64,
    #[prost(bytes="vec", tag="2")]
    pub market: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="3")]
    pub epoch: u32,
    #[prost(enumeration="StateField", tag="4")]
    pub field: i32,
    /// Mapping key when the field is a mapping entry (Aave: the underlying
    /// asset; COMPOUND_V2_TOTAL_CASH: the cToken as holder in the underlying);
    /// "" for scalar fields.
    #[prost(bytes="vec", tag="5")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    /// Exact decimal integer; "" means not carried, "0" is an observed zero.
    #[prost(string, tag="6")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub previous_value: ::prost::alloc::string::String,
    /// Fixed-point denominator of `value` as a decimal ("1", "1000000000000000",
    /// "1000000000000000000", "1000000000000000000000000000").
    #[prost(string, tag="8")]
    pub scale: ::prost::alloc::string::String,
    #[prost(enumeration="Observation", tag="9")]
    pub observation: i32,
    #[prost(enumeration="Boundary", tag="10")]
    pub boundary: i32,
    #[prost(enumeration="Scope", tag="11")]
    pub scope: i32,
    #[prost(uint64, tag="12")]
    pub ordinal: u64,
    #[prost(uint64, tag="13")]
    pub first_ordinal: u64,
    #[prost(uint32, tag="14")]
    pub change_count: u32,
    #[prost(uint32, tag="15")]
    pub transaction_index: u32,
    #[prost(bytes="vec", tag="16")]
    pub transaction_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="17")]
    pub call_index: u32,
    /// Meaningful for OBSERVATION_OBSERVED_LOG.
    #[prost(uint32, tag="18")]
    pub log_index: u32,
    /// Provenance. For QUALIFIED_CONSTANT rows `storage_contract` is the
    /// implementation whose code hash binds the value; slot and words are "".
    #[prost(bytes="vec", tag="19")]
    pub storage_contract: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="20")]
    pub storage_slot: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="21")]
    pub raw_previous_word: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="22")]
    pub raw_word: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="23")]
    pub bit_offset: u32,
    #[prost(uint32, tag="24")]
    pub bit_width: u32,
    #[prost(bool, tag="25")]
    pub signed: bool,
}
// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

/// Balance model family. `ModelEpoch.model_id` names the exact formula and
/// rounding chain inside a family; the executable definition is the Rust
/// conformance model of issue #16.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ModelFamily {
    Unspecified = 0,
    /// Aave V3 aToken: scaled balance x reserve normalized income (#13).
    AaveV3Atoken = 1,
    /// Compound v2 cToken shares x exchange-rate inputs (#14).
    CompoundV2Ctoken = 2,
    /// Compound III Comet signed base principal x base supply index (#15).
    CompoundV3Comet = 3,
    /// Lido stETH shares x totalPooledEther / totalShares (#23).
    LidoSteth = 4,
    /// ERC-4626 shares with an implementation-bound conversion (#24).
    Erc4626Vault = 5,
    /// Same-balance alias declaration only (Arc); no holder or global rows.
    AssetAlias = 6,
}
impl ModelFamily {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ModelFamily::Unspecified => "MODEL_FAMILY_UNSPECIFIED",
            ModelFamily::AaveV3Atoken => "MODEL_FAMILY_AAVE_V3_ATOKEN",
            ModelFamily::CompoundV2Ctoken => "MODEL_FAMILY_COMPOUND_V2_CTOKEN",
            ModelFamily::CompoundV3Comet => "MODEL_FAMILY_COMPOUND_V3_COMET",
            ModelFamily::LidoSteth => "MODEL_FAMILY_LIDO_STETH",
            ModelFamily::Erc4626Vault => "MODEL_FAMILY_ERC4626_VAULT",
            ModelFamily::AssetAlias => "MODEL_FAMILY_ASSET_ALIAS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MODEL_FAMILY_UNSPECIFIED" => Some(Self::Unspecified),
            "MODEL_FAMILY_AAVE_V3_ATOKEN" => Some(Self::AaveV3Atoken),
            "MODEL_FAMILY_COMPOUND_V2_CTOKEN" => Some(Self::CompoundV2Ctoken),
            "MODEL_FAMILY_COMPOUND_V3_COMET" => Some(Self::CompoundV3Comet),
            "MODEL_FAMILY_LIDO_STETH" => Some(Self::LidoSteth),
            "MODEL_FAMILY_ERC4626_VAULT" => Some(Self::Erc4626Vault),
            "MODEL_FAMILY_ASSET_ALIAS" => Some(Self::AssetAlias),
            _ => None,
        }
    }
}
/// What kind of number a holder basis is. It decides the sign rule and, with
/// the epoch's scale and rounding, the conversion to an observable balance.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BasisKind {
    Unspecified = 0,
    /// Unsigned amount multiplied by a global index and divided by the epoch
    /// `basis_scale` (Aave V3 scaled balance, low 120 bits since v3.4).
    ScaledBalance = 1,
    /// Unsigned share count converted through a ratio of global totals (cToken
    /// `accountTokens`, stETH `shares`, ERC-4626 shares, Maker Pot `pie`).
    Shares = 2,
    /// Signed principal (Comet `UserBasic.principal`, int104). Negative values
    /// are borrow debt and never an ERC-20 supply balance; `value` keeps the
    /// sign and is never clamped.
    SignedPrincipal = 3,
    /// Unsigned scaled debt basis (Aave variable debt). Deferred scope; listed so
    /// debt can never be mislabeled as a supply basis.
    ScaledDebt = 4,
}
impl BasisKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            BasisKind::Unspecified => "BASIS_KIND_UNSPECIFIED",
            BasisKind::ScaledBalance => "BASIS_KIND_SCALED_BALANCE",
            BasisKind::Shares => "BASIS_KIND_SHARES",
            BasisKind::SignedPrincipal => "BASIS_KIND_SIGNED_PRINCIPAL",
            BasisKind::ScaledDebt => "BASIS_KIND_SCALED_DEBT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BASIS_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "BASIS_KIND_SCALED_BALANCE" => Some(Self::ScaledBalance),
            "BASIS_KIND_SHARES" => Some(Self::Shares),
            "BASIS_KIND_SIGNED_PRINCIPAL" => Some(Self::SignedPrincipal),
            "BASIS_KIND_SCALED_DEBT" => Some(Self::ScaledDebt),
            _ => None,
        }
    }
}
/// How the value in a row was established.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Observation {
    Unspecified = 0,
    /// A persisted storage or balance write observed in this block. The row
    /// states this one field only; it is never a complete snapshot of anything
    /// else.
    ObservedWrite = 1,
    /// Decoded from a persisted log that restates a value in full (Lido
    /// `TokenRebased` post-report totals).
    ObservedLog = 2,
    /// A value bound at qualification rather than read from this block: a
    /// source constant, a code immutable pinned to a code hash, a deployment
    /// invariant, or a caller parameter echoed for audit. The map checks the
    /// pinned identity whenever the block carries a code change or pointer write.
    QualifiedConstant = 3,
    /// Computed by the map as a pure function of rows of the SAME block. Emitted
    /// only when every input was observed in this block; a map holds no state
    /// across blocks. Inputs are always emitted as their own rows.
    Derived = 4,
}
impl Observation {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Observation::Unspecified => "OBSERVATION_UNSPECIFIED",
            Observation::ObservedWrite => "OBSERVATION_OBSERVED_WRITE",
            Observation::ObservedLog => "OBSERVATION_OBSERVED_LOG",
            Observation::QualifiedConstant => "OBSERVATION_QUALIFIED_CONSTANT",
            Observation::Derived => "OBSERVATION_DERIVED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OBSERVATION_UNSPECIFIED" => Some(Self::Unspecified),
            "OBSERVATION_OBSERVED_WRITE" => Some(Self::ObservedWrite),
            "OBSERVATION_OBSERVED_LOG" => Some(Self::ObservedLog),
            "OBSERVATION_QUALIFIED_CONSTANT" => Some(Self::QualifiedConstant),
            "OBSERVATION_DERIVED" => Some(Self::Derived),
            _ => None,
        }
    }
}
/// Whether a row is an intra-block change boundary, the end-of-block value, or
/// a declaration with no write of its own.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Boundary {
    Unspecified = 0,
    /// One persisted write at `ordinal`; `change_count` is 1. Emitted only when
    /// the package parameter `emit_intermediate_changes` is true.
    Change = 1,
    /// Value after the last persisted write of the block, reduced over every
    /// write of the key in execution order. `previous_value` is the value before
    /// the first write, `first_ordinal` its ordinal, `ordinal` the last write's
    /// ordinal. Always emitted for every key written in the block; matches the
    /// end-of-block semantics of `evm.balances.v1`.
    EndOfBlock = 2,
    /// A qualified constant or parameter row; `ordinal` is the epoch boundary
    /// ordinal.
    Declaration = 3,
}
impl Boundary {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Boundary::Unspecified => "BOUNDARY_UNSPECIFIED",
            Boundary::Change => "BOUNDARY_CHANGE",
            Boundary::EndOfBlock => "BOUNDARY_END_OF_BLOCK",
            Boundary::Declaration => "BOUNDARY_DECLARATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BOUNDARY_UNSPECIFIED" => Some(Self::Unspecified),
            "BOUNDARY_CHANGE" => Some(Self::Change),
            "BOUNDARY_END_OF_BLOCK" => Some(Self::EndOfBlock),
            "BOUNDARY_DECLARATION" => Some(Self::Declaration),
            _ => None,
        }
    }
}
/// Execution scope of the persisted effect. Rows outside TRANSACTION scope have
/// an empty `transaction_hash`; `transaction_index` and `call_index` are then
/// meaningless.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Scope {
    Unspecified = 0,
    /// A call with `state_reverted == false` inside a SUCCEEDED transaction.
    Transaction = 1,
    /// `Block.system_calls\[\]` with `state_reverted == false`; `call_index` is
    /// the system call index.
    SystemCall = 2,
    /// `Block.balance_changes` / `Block.code_changes` records.
    Block = 3,
    /// Declared at an epoch boundary or heartbeat; no persisted write.
    Epoch = 4,
}
impl Scope {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Scope::Unspecified => "SCOPE_UNSPECIFIED",
            Scope::Transaction => "SCOPE_TRANSACTION",
            Scope::SystemCall => "SCOPE_SYSTEM_CALL",
            Scope::Block => "SCOPE_BLOCK",
            Scope::Epoch => "SCOPE_EPOCH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SCOPE_UNSPECIFIED" => Some(Self::Unspecified),
            "SCOPE_TRANSACTION" => Some(Self::Transaction),
            "SCOPE_SYSTEM_CALL" => Some(Self::SystemCall),
            "SCOPE_BLOCK" => Some(Self::Block),
            "SCOPE_EPOCH" => Some(Self::Epoch),
            _ => None,
        }
    }
}
/// Lifecycle of a (market, epoch) model binding.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EpochEventKind {
    Unspecified = 0,
    /// Emitted once at the activation block with the full binding.
    Bound = 1,
    /// Full binding restated every `epoch_heartbeat_blocks` so a consumer that
    /// joins mid-stream recovers it without a competing bootstrap mechanism.
    Reaffirmed = 2,
    /// The previous epoch ended at (block, ordinal) for `reason`, with the
    /// on-chain evidence cited and verified against the block. Immediately
    /// followed by the BOUND row of the next epoch, or by SUSPENDED.
    Invalidated = 3,
    /// The market has no qualified model from here on (unsupported model).
    /// Declared by parameters, never inferred. Retained state for the market
    /// must not be evaluated past this point. A live write the bound layout
    /// cannot describe is not a row: it fails the block.
    Suspended = 4,
}
impl EpochEventKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            EpochEventKind::Unspecified => "EPOCH_EVENT_KIND_UNSPECIFIED",
            EpochEventKind::Bound => "EPOCH_EVENT_KIND_BOUND",
            EpochEventKind::Reaffirmed => "EPOCH_EVENT_KIND_REAFFIRMED",
            EpochEventKind::Invalidated => "EPOCH_EVENT_KIND_INVALIDATED",
            EpochEventKind::Suspended => "EPOCH_EVENT_KIND_SUSPENDED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EPOCH_EVENT_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "EPOCH_EVENT_KIND_BOUND" => Some(Self::Bound),
            "EPOCH_EVENT_KIND_REAFFIRMED" => Some(Self::Reaffirmed),
            "EPOCH_EVENT_KIND_INVALIDATED" => Some(Self::Invalidated),
            "EPOCH_EVENT_KIND_SUSPENDED" => Some(Self::Suspended),
            _ => None,
        }
    }
}
/// Why an epoch ended.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum InvalidationReason {
    Unspecified = 0,
    /// Persisted write to the market's implementation pointer slot.
    ImplementationPointerWrite = 1,
    /// Persisted `CodeChange` on the market itself.
    CodeChange = 2,
    /// Persisted `CodeChange` on a dependency contract.
    DependencyCodeChange = 3,
    /// Persisted write to a dependency's pointer slot (beacon, locator, pool).
    DependencyPointerWrite = 4,
    /// Persisted write to the slot holding a rate-model address, or new rate
    /// immutables through a new implementation.
    RateModelChange = 5,
    /// Persisted write to a contract-version slot (Lido `contractVersion`).
    ContractVersionSet = 6,
    /// A qualified storage-layout migration (Lido totalShares slot move).
    StorageMigration = 7,
    /// Operator-declared boundary without an on-chain trigger; evidence empty.
    ParameterRebind = 8,
    /// SUSPENDED only: the era starting here was never qualified.
    UnqualifiedEra = 9,
}
impl InvalidationReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            InvalidationReason::Unspecified => "INVALIDATION_REASON_UNSPECIFIED",
            InvalidationReason::ImplementationPointerWrite => "INVALIDATION_REASON_IMPLEMENTATION_POINTER_WRITE",
            InvalidationReason::CodeChange => "INVALIDATION_REASON_CODE_CHANGE",
            InvalidationReason::DependencyCodeChange => "INVALIDATION_REASON_DEPENDENCY_CODE_CHANGE",
            InvalidationReason::DependencyPointerWrite => "INVALIDATION_REASON_DEPENDENCY_POINTER_WRITE",
            InvalidationReason::RateModelChange => "INVALIDATION_REASON_RATE_MODEL_CHANGE",
            InvalidationReason::ContractVersionSet => "INVALIDATION_REASON_CONTRACT_VERSION_SET",
            InvalidationReason::StorageMigration => "INVALIDATION_REASON_STORAGE_MIGRATION",
            InvalidationReason::ParameterRebind => "INVALIDATION_REASON_PARAMETER_REBIND",
            InvalidationReason::UnqualifiedEra => "INVALIDATION_REASON_UNQUALIFIED_ERA",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INVALIDATION_REASON_UNSPECIFIED" => Some(Self::Unspecified),
            "INVALIDATION_REASON_IMPLEMENTATION_POINTER_WRITE" => Some(Self::ImplementationPointerWrite),
            "INVALIDATION_REASON_CODE_CHANGE" => Some(Self::CodeChange),
            "INVALIDATION_REASON_DEPENDENCY_CODE_CHANGE" => Some(Self::DependencyCodeChange),
            "INVALIDATION_REASON_DEPENDENCY_POINTER_WRITE" => Some(Self::DependencyPointerWrite),
            "INVALIDATION_REASON_RATE_MODEL_CHANGE" => Some(Self::RateModelChange),
            "INVALIDATION_REASON_CONTRACT_VERSION_SET" => Some(Self::ContractVersionSet),
            "INVALIDATION_REASON_STORAGE_MIGRATION" => Some(Self::StorageMigration),
            "INVALIDATION_REASON_PARAMETER_REBIND" => Some(Self::ParameterRebind),
            "INVALIDATION_REASON_UNQUALIFIED_ERA" => Some(Self::UnqualifiedEra),
            _ => None,
        }
    }
}
/// Role of a dependency edge in the evaluation graph.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DependencyRole {
    Unspecified = 0,
    /// Logic contract executing behind the market proxy.
    Implementation = 1,
    /// Beacon or kernel resolving the implementation.
    Beacon = 2,
    /// Admin allowed to move the pointer.
    ProxyAdmin = 3,
    /// Pool or core contract storing the shared index or rate (Aave Pool).
    Pool = 4,
    /// Underlying asset whose storage is a cross-contract input (USDC for
    /// cUSDC cash) or the asset a vault converts into.
    Underlying = 5,
    /// Interest-rate model contract (Compound v2 JumpRateModelV2).
    InterestRateModel = 6,
    /// External rate accumulator (Maker Pot for sDAI and cDAI).
    RateAccumulator = 7,
    /// Contract authorized to write report-driven state (Lido Accounting).
    Accounting = 8,
    /// Asset wrapped by a vault (aToken wrapped by a static aToken).
    WrappedAsset = 9,
}
impl DependencyRole {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            DependencyRole::Unspecified => "DEPENDENCY_ROLE_UNSPECIFIED",
            DependencyRole::Implementation => "DEPENDENCY_ROLE_IMPLEMENTATION",
            DependencyRole::Beacon => "DEPENDENCY_ROLE_BEACON",
            DependencyRole::ProxyAdmin => "DEPENDENCY_ROLE_PROXY_ADMIN",
            DependencyRole::Pool => "DEPENDENCY_ROLE_POOL",
            DependencyRole::Underlying => "DEPENDENCY_ROLE_UNDERLYING",
            DependencyRole::InterestRateModel => "DEPENDENCY_ROLE_INTEREST_RATE_MODEL",
            DependencyRole::RateAccumulator => "DEPENDENCY_ROLE_RATE_ACCUMULATOR",
            DependencyRole::Accounting => "DEPENDENCY_ROLE_ACCOUNTING",
            DependencyRole::WrappedAsset => "DEPENDENCY_ROLE_WRAPPED_ASSET",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DEPENDENCY_ROLE_UNSPECIFIED" => Some(Self::Unspecified),
            "DEPENDENCY_ROLE_IMPLEMENTATION" => Some(Self::Implementation),
            "DEPENDENCY_ROLE_BEACON" => Some(Self::Beacon),
            "DEPENDENCY_ROLE_PROXY_ADMIN" => Some(Self::ProxyAdmin),
            "DEPENDENCY_ROLE_POOL" => Some(Self::Pool),
            "DEPENDENCY_ROLE_UNDERLYING" => Some(Self::Underlying),
            "DEPENDENCY_ROLE_INTEREST_RATE_MODEL" => Some(Self::InterestRateModel),
            "DEPENDENCY_ROLE_RATE_ACCUMULATOR" => Some(Self::RateAccumulator),
            "DEPENDENCY_ROLE_ACCOUNTING" => Some(Self::Accounting),
            "DEPENDENCY_ROLE_WRAPPED_ASSET" => Some(Self::WrappedAsset),
            _ => None,
        }
    }
}
/// How a dependency identity is bound and checked.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BindingKind {
    Unspecified = 0,
    /// Runtime code hash pinned; any persisted `CodeChange` invalidates.
    CodeHash = 1,
    /// Resolved through a storage pointer whose expected word is
    /// `pointer_value`; any persisted write to that slot invalidates, including
    /// a write back to the same value.
    StoragePointer = 2,
    /// Declared by parameters only; no on-chain check from block data.
    Declared = 3,
}
impl BindingKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            BindingKind::Unspecified => "BINDING_KIND_UNSPECIFIED",
            BindingKind::CodeHash => "BINDING_KIND_CODE_HASH",
            BindingKind::StoragePointer => "BINDING_KIND_STORAGE_POINTER",
            BindingKind::Declared => "BINDING_KIND_DECLARED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BINDING_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "BINDING_KIND_CODE_HASH" => Some(Self::CodeHash),
            "BINDING_KIND_STORAGE_POINTER" => Some(Self::StoragePointer),
            "BINDING_KIND_DECLARED" => Some(Self::Declared),
            _ => None,
        }
    }
}
/// Integer rounding direction of a bound conversion.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Rounding {
    Unspecified = 0,
    Floor = 1,
    Ceil = 2,
    HalfUp = 3,
}
impl Rounding {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Rounding::Unspecified => "ROUNDING_UNSPECIFIED",
            Rounding::Floor => "ROUNDING_FLOOR",
            Rounding::Ceil => "ROUNDING_CEIL",
            Rounding::HalfUp => "ROUNDING_HALF_UP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ROUNDING_UNSPECIFIED" => Some(Self::Unspecified),
            "ROUNDING_FLOOR" => Some(Self::Floor),
            "ROUNDING_CEIL" => Some(Self::Ceil),
            "ROUNDING_HALF_UP" => Some(Self::HalfUp),
            _ => None,
        }
    }
}
/// Kind of same-balance alias.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AliasKind {
    Unspecified = 0,
    /// `asset` exposes the SAME balance as `alias_of` at another precision:
    /// asset_amount = round(alias_of_amount * asset_scale / alias_of_scale).
    /// Arc: ERC-20 USDC 0x3600...0000 (6 decimals) over native USDC (18).
    PrecisionView = 1,
}
impl AliasKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            AliasKind::Unspecified => "ALIAS_KIND_UNSPECIFIED",
            AliasKind::PrecisionView => "ALIAS_KIND_PRECISION_VIEW",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ALIAS_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "ALIAS_KIND_PRECISION_VIEW" => Some(Self::PrecisionView),
            _ => None,
        }
    }
}
/// Protocol-specific global state fields. Numeric ranges are reserved per
/// family; values are append-only and never renumbered.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StateField {
    Unspecified = 0,
    /// Aave V3 `DataTypes.ReserveData` in Pool storage, `key` = underlying
    /// asset. Indices and rates are ray (scale 1e27); timestamps are seconds.
    AaveLiquidityIndex = 1,
    AaveCurrentLiquidityRate = 2,
    AaveLastUpdateTimestamp = 3,
    AaveVariableBorrowIndex = 4,
    AaveCurrentVariableBorrowRate = 5,
    /// Packed reserve configuration word (active/paused/frozen bits); gates
    /// withdrawability, not conversion.
    AaveReserveConfiguration = 6,
    /// Compound v2 `CTokenStorage` and the cross-contract cash input.
    /// Mantissas are 1e18-scaled; block numbers and totals are scale 1.
    /// TOTAL_CASH is read from the cash source (underlying ERC-20 balance of the
    /// cToken, the market's native balance, or Pot pie x chi); `key` = cToken.
    CompoundV2TotalCash = 10,
    CompoundV2TotalBorrows = 11,
    CompoundV2TotalReserves = 12,
    CompoundV2TotalSupply = 13,
    CompoundV2BorrowIndex = 14,
    CompoundV2AccrualBlockNumber = 15,
    CompoundV2ReserveFactorMantissa = 16,
    CompoundV2InitialExchangeRateMantissa = 17,
    /// Rate-model contract identity as a 20-byte value in `value` (decimal of
    /// the address) is not used; the identity is a Dependency edge. These are
    /// the model's storage parameters.
    CompoundV2IrmBaseRatePerBlock = 20,
    CompoundV2IrmMultiplierPerBlock = 21,
    CompoundV2IrmJumpMultiplierPerBlock = 22,
    CompoundV2IrmKink = 23,
    CompoundV2IrmBlocksPerYear = 24,
    /// Compound III `CometStorage` packed market state plus implementation
    /// immutables and constants. Indices scale 1e15 (BASE_INDEX_SCALE); rates
    /// and kinks are 1e18 factors per second; totals are base-token raw units.
    CometBaseSupplyIndex = 30,
    CometBaseBorrowIndex = 31,
    CometTotalSupplyBase = 32,
    CometTotalBorrowBase = 33,
    CometLastAccrualTime = 34,
    CometPauseFlags = 35,
    CometSupplyKink = 40,
    CometSupplyRateSlopeLow = 41,
    CometSupplyRateSlopeHigh = 42,
    CometSupplyRateBase = 43,
    CometBorrowKink = 44,
    CometBorrowRateSlopeLow = 45,
    CometBorrowRateSlopeHigh = 46,
    CometBorrowRateBase = 47,
    CometBaseScale = 48,
    CometBaseIndexScale = 49,
    CometFactorScale = 50,
    /// Lido unstructured storage. Shares and ether are raw wei-scale integers.
    /// Slots differ per contract version; each row cites the slot it read.
    LidoTotalShares = 60,
    LidoExternalShares = 61,
    LidoBufferedEther = 62,
    LidoDepositedPostReport = 63,
    LidoClValidatorsBalance = 64,
    LidoClPendingBalance = 65,
    LidoContractVersion = 66,
    /// internalEther + externalShares x internalEther / internalShares. Only
    /// OBSERVATION_DERIVED, and only when every input was observed in-block.
    LidoTotalPooledEther = 67,
    /// `TokenRebased` log fields (OBSERVATION_OBSERVED_LOG): the post-report
    /// share rate is postTotalEther / postTotalShares.
    LidoReportTimestamp = 68,
    LidoReportPostTotalShares = 69,
    LidoReportPostTotalEther = 70,
    LidoReportSharesMintedAsFees = 71,
    /// Maker Pot (dependency of sDAI convertToAssets and of cDAI cash). chi and
    /// dsr are ray; rho is seconds; pie is a per-account share (HolderBasis).
    MakerPotChi = 80,
    MakerPotRho = 81,
    MakerPotDsr = 82,
    /// ERC-4626 generic inputs for OpenZeppelin virtual-offset vaults. Vaults
    /// bound to another model reuse that family's fields (static aToken ->
    /// AAVE_*, sDAI -> MAKER_POT_*).
    Erc4626TotalSupply = 90,
    Erc4626TotalAssets = 91,
    Erc4626DecimalsOffset = 92,
}
impl StateField {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            StateField::Unspecified => "STATE_FIELD_UNSPECIFIED",
            StateField::AaveLiquidityIndex => "STATE_FIELD_AAVE_LIQUIDITY_INDEX",
            StateField::AaveCurrentLiquidityRate => "STATE_FIELD_AAVE_CURRENT_LIQUIDITY_RATE",
            StateField::AaveLastUpdateTimestamp => "STATE_FIELD_AAVE_LAST_UPDATE_TIMESTAMP",
            StateField::AaveVariableBorrowIndex => "STATE_FIELD_AAVE_VARIABLE_BORROW_INDEX",
            StateField::AaveCurrentVariableBorrowRate => "STATE_FIELD_AAVE_CURRENT_VARIABLE_BORROW_RATE",
            StateField::AaveReserveConfiguration => "STATE_FIELD_AAVE_RESERVE_CONFIGURATION",
            StateField::CompoundV2TotalCash => "STATE_FIELD_COMPOUND_V2_TOTAL_CASH",
            StateField::CompoundV2TotalBorrows => "STATE_FIELD_COMPOUND_V2_TOTAL_BORROWS",
            StateField::CompoundV2TotalReserves => "STATE_FIELD_COMPOUND_V2_TOTAL_RESERVES",
            StateField::CompoundV2TotalSupply => "STATE_FIELD_COMPOUND_V2_TOTAL_SUPPLY",
            StateField::CompoundV2BorrowIndex => "STATE_FIELD_COMPOUND_V2_BORROW_INDEX",
            StateField::CompoundV2AccrualBlockNumber => "STATE_FIELD_COMPOUND_V2_ACCRUAL_BLOCK_NUMBER",
            StateField::CompoundV2ReserveFactorMantissa => "STATE_FIELD_COMPOUND_V2_RESERVE_FACTOR_MANTISSA",
            StateField::CompoundV2InitialExchangeRateMantissa => "STATE_FIELD_COMPOUND_V2_INITIAL_EXCHANGE_RATE_MANTISSA",
            StateField::CompoundV2IrmBaseRatePerBlock => "STATE_FIELD_COMPOUND_V2_IRM_BASE_RATE_PER_BLOCK",
            StateField::CompoundV2IrmMultiplierPerBlock => "STATE_FIELD_COMPOUND_V2_IRM_MULTIPLIER_PER_BLOCK",
            StateField::CompoundV2IrmJumpMultiplierPerBlock => "STATE_FIELD_COMPOUND_V2_IRM_JUMP_MULTIPLIER_PER_BLOCK",
            StateField::CompoundV2IrmKink => "STATE_FIELD_COMPOUND_V2_IRM_KINK",
            StateField::CompoundV2IrmBlocksPerYear => "STATE_FIELD_COMPOUND_V2_IRM_BLOCKS_PER_YEAR",
            StateField::CometBaseSupplyIndex => "STATE_FIELD_COMET_BASE_SUPPLY_INDEX",
            StateField::CometBaseBorrowIndex => "STATE_FIELD_COMET_BASE_BORROW_INDEX",
            StateField::CometTotalSupplyBase => "STATE_FIELD_COMET_TOTAL_SUPPLY_BASE",
            StateField::CometTotalBorrowBase => "STATE_FIELD_COMET_TOTAL_BORROW_BASE",
            StateField::CometLastAccrualTime => "STATE_FIELD_COMET_LAST_ACCRUAL_TIME",
            StateField::CometPauseFlags => "STATE_FIELD_COMET_PAUSE_FLAGS",
            StateField::CometSupplyKink => "STATE_FIELD_COMET_SUPPLY_KINK",
            StateField::CometSupplyRateSlopeLow => "STATE_FIELD_COMET_SUPPLY_RATE_SLOPE_LOW",
            StateField::CometSupplyRateSlopeHigh => "STATE_FIELD_COMET_SUPPLY_RATE_SLOPE_HIGH",
            StateField::CometSupplyRateBase => "STATE_FIELD_COMET_SUPPLY_RATE_BASE",
            StateField::CometBorrowKink => "STATE_FIELD_COMET_BORROW_KINK",
            StateField::CometBorrowRateSlopeLow => "STATE_FIELD_COMET_BORROW_RATE_SLOPE_LOW",
            StateField::CometBorrowRateSlopeHigh => "STATE_FIELD_COMET_BORROW_RATE_SLOPE_HIGH",
            StateField::CometBorrowRateBase => "STATE_FIELD_COMET_BORROW_RATE_BASE",
            StateField::CometBaseScale => "STATE_FIELD_COMET_BASE_SCALE",
            StateField::CometBaseIndexScale => "STATE_FIELD_COMET_BASE_INDEX_SCALE",
            StateField::CometFactorScale => "STATE_FIELD_COMET_FACTOR_SCALE",
            StateField::LidoTotalShares => "STATE_FIELD_LIDO_TOTAL_SHARES",
            StateField::LidoExternalShares => "STATE_FIELD_LIDO_EXTERNAL_SHARES",
            StateField::LidoBufferedEther => "STATE_FIELD_LIDO_BUFFERED_ETHER",
            StateField::LidoDepositedPostReport => "STATE_FIELD_LIDO_DEPOSITED_POST_REPORT",
            StateField::LidoClValidatorsBalance => "STATE_FIELD_LIDO_CL_VALIDATORS_BALANCE",
            StateField::LidoClPendingBalance => "STATE_FIELD_LIDO_CL_PENDING_BALANCE",
            StateField::LidoContractVersion => "STATE_FIELD_LIDO_CONTRACT_VERSION",
            StateField::LidoTotalPooledEther => "STATE_FIELD_LIDO_TOTAL_POOLED_ETHER",
            StateField::LidoReportTimestamp => "STATE_FIELD_LIDO_REPORT_TIMESTAMP",
            StateField::LidoReportPostTotalShares => "STATE_FIELD_LIDO_REPORT_POST_TOTAL_SHARES",
            StateField::LidoReportPostTotalEther => "STATE_FIELD_LIDO_REPORT_POST_TOTAL_ETHER",
            StateField::LidoReportSharesMintedAsFees => "STATE_FIELD_LIDO_REPORT_SHARES_MINTED_AS_FEES",
            StateField::MakerPotChi => "STATE_FIELD_MAKER_POT_CHI",
            StateField::MakerPotRho => "STATE_FIELD_MAKER_POT_RHO",
            StateField::MakerPotDsr => "STATE_FIELD_MAKER_POT_DSR",
            StateField::Erc4626TotalSupply => "STATE_FIELD_ERC4626_TOTAL_SUPPLY",
            StateField::Erc4626TotalAssets => "STATE_FIELD_ERC4626_TOTAL_ASSETS",
            StateField::Erc4626DecimalsOffset => "STATE_FIELD_ERC4626_DECIMALS_OFFSET",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STATE_FIELD_UNSPECIFIED" => Some(Self::Unspecified),
            "STATE_FIELD_AAVE_LIQUIDITY_INDEX" => Some(Self::AaveLiquidityIndex),
            "STATE_FIELD_AAVE_CURRENT_LIQUIDITY_RATE" => Some(Self::AaveCurrentLiquidityRate),
            "STATE_FIELD_AAVE_LAST_UPDATE_TIMESTAMP" => Some(Self::AaveLastUpdateTimestamp),
            "STATE_FIELD_AAVE_VARIABLE_BORROW_INDEX" => Some(Self::AaveVariableBorrowIndex),
            "STATE_FIELD_AAVE_CURRENT_VARIABLE_BORROW_RATE" => Some(Self::AaveCurrentVariableBorrowRate),
            "STATE_FIELD_AAVE_RESERVE_CONFIGURATION" => Some(Self::AaveReserveConfiguration),
            "STATE_FIELD_COMPOUND_V2_TOTAL_CASH" => Some(Self::CompoundV2TotalCash),
            "STATE_FIELD_COMPOUND_V2_TOTAL_BORROWS" => Some(Self::CompoundV2TotalBorrows),
            "STATE_FIELD_COMPOUND_V2_TOTAL_RESERVES" => Some(Self::CompoundV2TotalReserves),
            "STATE_FIELD_COMPOUND_V2_TOTAL_SUPPLY" => Some(Self::CompoundV2TotalSupply),
            "STATE_FIELD_COMPOUND_V2_BORROW_INDEX" => Some(Self::CompoundV2BorrowIndex),
            "STATE_FIELD_COMPOUND_V2_ACCRUAL_BLOCK_NUMBER" => Some(Self::CompoundV2AccrualBlockNumber),
            "STATE_FIELD_COMPOUND_V2_RESERVE_FACTOR_MANTISSA" => Some(Self::CompoundV2ReserveFactorMantissa),
            "STATE_FIELD_COMPOUND_V2_INITIAL_EXCHANGE_RATE_MANTISSA" => Some(Self::CompoundV2InitialExchangeRateMantissa),
            "STATE_FIELD_COMPOUND_V2_IRM_BASE_RATE_PER_BLOCK" => Some(Self::CompoundV2IrmBaseRatePerBlock),
            "STATE_FIELD_COMPOUND_V2_IRM_MULTIPLIER_PER_BLOCK" => Some(Self::CompoundV2IrmMultiplierPerBlock),
            "STATE_FIELD_COMPOUND_V2_IRM_JUMP_MULTIPLIER_PER_BLOCK" => Some(Self::CompoundV2IrmJumpMultiplierPerBlock),
            "STATE_FIELD_COMPOUND_V2_IRM_KINK" => Some(Self::CompoundV2IrmKink),
            "STATE_FIELD_COMPOUND_V2_IRM_BLOCKS_PER_YEAR" => Some(Self::CompoundV2IrmBlocksPerYear),
            "STATE_FIELD_COMET_BASE_SUPPLY_INDEX" => Some(Self::CometBaseSupplyIndex),
            "STATE_FIELD_COMET_BASE_BORROW_INDEX" => Some(Self::CometBaseBorrowIndex),
            "STATE_FIELD_COMET_TOTAL_SUPPLY_BASE" => Some(Self::CometTotalSupplyBase),
            "STATE_FIELD_COMET_TOTAL_BORROW_BASE" => Some(Self::CometTotalBorrowBase),
            "STATE_FIELD_COMET_LAST_ACCRUAL_TIME" => Some(Self::CometLastAccrualTime),
            "STATE_FIELD_COMET_PAUSE_FLAGS" => Some(Self::CometPauseFlags),
            "STATE_FIELD_COMET_SUPPLY_KINK" => Some(Self::CometSupplyKink),
            "STATE_FIELD_COMET_SUPPLY_RATE_SLOPE_LOW" => Some(Self::CometSupplyRateSlopeLow),
            "STATE_FIELD_COMET_SUPPLY_RATE_SLOPE_HIGH" => Some(Self::CometSupplyRateSlopeHigh),
            "STATE_FIELD_COMET_SUPPLY_RATE_BASE" => Some(Self::CometSupplyRateBase),
            "STATE_FIELD_COMET_BORROW_KINK" => Some(Self::CometBorrowKink),
            "STATE_FIELD_COMET_BORROW_RATE_SLOPE_LOW" => Some(Self::CometBorrowRateSlopeLow),
            "STATE_FIELD_COMET_BORROW_RATE_SLOPE_HIGH" => Some(Self::CometBorrowRateSlopeHigh),
            "STATE_FIELD_COMET_BORROW_RATE_BASE" => Some(Self::CometBorrowRateBase),
            "STATE_FIELD_COMET_BASE_SCALE" => Some(Self::CometBaseScale),
            "STATE_FIELD_COMET_BASE_INDEX_SCALE" => Some(Self::CometBaseIndexScale),
            "STATE_FIELD_COMET_FACTOR_SCALE" => Some(Self::CometFactorScale),
            "STATE_FIELD_LIDO_TOTAL_SHARES" => Some(Self::LidoTotalShares),
            "STATE_FIELD_LIDO_EXTERNAL_SHARES" => Some(Self::LidoExternalShares),
            "STATE_FIELD_LIDO_BUFFERED_ETHER" => Some(Self::LidoBufferedEther),
            "STATE_FIELD_LIDO_DEPOSITED_POST_REPORT" => Some(Self::LidoDepositedPostReport),
            "STATE_FIELD_LIDO_CL_VALIDATORS_BALANCE" => Some(Self::LidoClValidatorsBalance),
            "STATE_FIELD_LIDO_CL_PENDING_BALANCE" => Some(Self::LidoClPendingBalance),
            "STATE_FIELD_LIDO_CONTRACT_VERSION" => Some(Self::LidoContractVersion),
            "STATE_FIELD_LIDO_TOTAL_POOLED_ETHER" => Some(Self::LidoTotalPooledEther),
            "STATE_FIELD_LIDO_REPORT_TIMESTAMP" => Some(Self::LidoReportTimestamp),
            "STATE_FIELD_LIDO_REPORT_POST_TOTAL_SHARES" => Some(Self::LidoReportPostTotalShares),
            "STATE_FIELD_LIDO_REPORT_POST_TOTAL_ETHER" => Some(Self::LidoReportPostTotalEther),
            "STATE_FIELD_LIDO_REPORT_SHARES_MINTED_AS_FEES" => Some(Self::LidoReportSharesMintedAsFees),
            "STATE_FIELD_MAKER_POT_CHI" => Some(Self::MakerPotChi),
            "STATE_FIELD_MAKER_POT_RHO" => Some(Self::MakerPotRho),
            "STATE_FIELD_MAKER_POT_DSR" => Some(Self::MakerPotDsr),
            "STATE_FIELD_ERC4626_TOTAL_SUPPLY" => Some(Self::Erc4626TotalSupply),
            "STATE_FIELD_ERC4626_TOTAL_ASSETS" => Some(Self::Erc4626TotalAssets),
            "STATE_FIELD_ERC4626_DECIMALS_OFFSET" => Some(Self::Erc4626DecimalsOffset),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
