// @generated by buffa-codegen. DO NOT EDIT.

include!("executions.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("executions.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("executions.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::EventsView;
#[doc(inline)]
pub use self::__buffa::view::EventsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::EventsLazyView;
#[doc(inline)]
pub use self::__buffa::view::BlockClockView;
#[doc(inline)]
pub use self::__buffa::view::BlockClockOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BlockClockLazyView;
#[doc(inline)]
pub use self::__buffa::view::TransactionView;
#[doc(inline)]
pub use self::__buffa::view::TransactionOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TransactionLazyView;
#[doc(inline)]
pub use self::__buffa::view::CallView;
#[doc(inline)]
pub use self::__buffa::view::CallOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::CallLazyView;
#[doc(inline)]
pub use self::__buffa::view::LogView;
#[doc(inline)]
pub use self::__buffa::view::LogOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::LogLazyView;
#[doc(inline)]
pub use self::__buffa::view::CodeChangeView;
#[doc(inline)]
pub use self::__buffa::view::CodeChangeOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::CodeChangeLazyView;
#[doc(inline)]
pub use self::__buffa::view::SetCodeAuthorizationView;
#[doc(inline)]
pub use self::__buffa::view::SetCodeAuthorizationOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::SetCodeAuthorizationLazyView;
