// @generated by buffa-codegen. DO NOT EDIT.
// source: uniswap-v3-pool-state.proto

/// Complete block envelope for state reconstruction. Each pool's changes are in
/// canonical log order. This is not a standalone price or liquidity snapshot:
/// consumers need a verified initial state and uninterrupted block continuity.
#[derive(Clone, Debug, Default)]
pub struct BlockPoolChangesView<'a> {
    /// Field 1: `block_number`
    pub block_number: u64,
    /// Field 2: `block_hash`
    pub block_hash: &'a [u8],
    /// Field 3: `parent_hash`
    pub parent_hash: &'a [u8],
    /// Field 4: `timestamp_seconds`
    pub timestamp_seconds: i64,
    /// Field 5: `timestamp_nanos`
    pub timestamp_nanos: i32,
    /// Field 6: `pools`
    pub pools: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::PoolChangesView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for BlockPoolChangesView<'a> {
    type Owned = super::super::BlockPoolChanges;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_number = ::buffa::types::decode_uint64(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.block_hash = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.parent_hash = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp_seconds = ::buffa::types::decode_int64(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp_nanos = ::buffa::types::decode_int32(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::PoolChangesView,
                    >(),
                )?;
                view.pools
                    .push(
                        <super::super::__buffa::view::PoolChangesView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::BlockPoolChanges, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::BlockPoolChanges, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::BlockPoolChanges {
            block_number: self.block_number,
            block_hash: (self.block_hash).to_vec(),
            parent_hash: (self.parent_hash).to_vec(),
            timestamp_seconds: self.timestamp_seconds,
            timestamp_nanos: self.timestamp_nanos,
            pools: self
                .pools
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for BlockPoolChangesView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.block_number != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_number) as u64;
        }
        if !self.block_hash.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.block_hash) as u64;
        }
        if !self.parent_hash.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.parent_hash) as u64;
        }
        if self.timestamp_seconds != 0i64 {
            size
                += 1u64
                    + ::buffa::types::int64_encoded_len(self.timestamp_seconds) as u64;
        }
        if self.timestamp_nanos != 0i32 {
            size
                += 1u64 + ::buffa::types::int32_encoded_len(self.timestamp_nanos) as u64;
        }
        for v in &self.pools {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.block_number != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.block_number, buf);
        }
        if !self.block_hash.is_empty() {
            ::buffa::types::put_shared_bytes_field(2u32, &self.block_hash, buf);
        }
        if !self.parent_hash.is_empty() {
            ::buffa::types::put_shared_bytes_field(3u32, &self.parent_hash, buf);
        }
        if self.timestamp_seconds != 0i64 {
            ::buffa::types::put_int64_field(4u32, self.timestamp_seconds, buf);
        }
        if self.timestamp_nanos != 0i32 {
            ::buffa::types::put_int32_field(5u32, self.timestamp_nanos, buf);
        }
        for v in &self.pools {
            ::buffa::types::put_len_delimited_header(
                6u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for BlockPoolChangesView<'a> {
    const PACKAGE: &'static str = "uniswap.v3";
    const NAME: &'static str = "BlockPoolChanges";
    const FULL_NAME: &'static str = "uniswap.v3.BlockPoolChanges";
    const TYPE_URL: &'static str = "type.googleapis.com/uniswap.v3.BlockPoolChanges";
}
::buffa::impl_default_view_instance!(BlockPoolChangesView);
::buffa::impl_view_reborrow!(BlockPoolChangesView);
/** Self-contained, `'static` owned view of a `BlockPoolChanges` message.

 Wraps [`::buffa::OwnedView`]`<`[`BlockPoolChangesView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`BlockPoolChangesView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct BlockPoolChangesOwnedView(::buffa::OwnedView<BlockPoolChangesView<'static>>);
impl BlockPoolChangesOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            BlockPoolChangesOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            BlockPoolChangesOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::BlockPoolChanges,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            BlockPoolChangesOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`BlockPoolChangesView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &BlockPoolChangesView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::BlockPoolChanges {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `block_number`
    #[must_use]
    pub fn block_number(&self) -> u64 {
        self.0.reborrow().block_number
    }
    /// Field 2: `block_hash`
    #[must_use]
    pub fn block_hash(&self) -> &'_ [u8] {
        self.0.reborrow().block_hash
    }
    /// Field 3: `parent_hash`
    #[must_use]
    pub fn parent_hash(&self) -> &'_ [u8] {
        self.0.reborrow().parent_hash
    }
    /// Field 4: `timestamp_seconds`
    #[must_use]
    pub fn timestamp_seconds(&self) -> i64 {
        self.0.reborrow().timestamp_seconds
    }
    /// Field 5: `timestamp_nanos`
    #[must_use]
    pub fn timestamp_nanos(&self) -> i32 {
        self.0.reborrow().timestamp_nanos
    }
    /// Field 6: `pools`
    #[must_use]
    pub fn pools(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::PoolChangesView<'_>> {
        &self.0.reborrow().pools
    }
}
impl ::core::convert::From<::buffa::OwnedView<BlockPoolChangesView<'static>>>
for BlockPoolChangesOwnedView {
    fn from(inner: ::buffa::OwnedView<BlockPoolChangesView<'static>>) -> Self {
        BlockPoolChangesOwnedView(inner)
    }
}
impl ::core::convert::From<BlockPoolChangesOwnedView>
for ::buffa::OwnedView<BlockPoolChangesView<'static>> {
    fn from(wrapper: BlockPoolChangesOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<BlockPoolChangesView<'static>>>
for BlockPoolChangesOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<BlockPoolChangesView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::BlockPoolChanges {
    type View<'a> = BlockPoolChangesView<'a>;
    type ViewHandle = BlockPoolChangesOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct PoolChangesView<'a> {
    /// Field 1: `pool`
    pub pool: &'a [u8],
    /// Field 2: `changes`
    pub changes: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::PoolChangeView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for PoolChangesView<'a> {
    type Owned = super::super::PoolChanges;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.pool = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<super::super::__buffa::view::PoolChangeView>(),
                )?;
                view.changes
                    .push(
                        <super::super::__buffa::view::PoolChangeView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::PoolChanges, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::PoolChanges, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::PoolChanges {
            pool: (self.pool).to_vec(),
            changes: self
                .changes
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for PoolChangesView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.pool.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.pool) as u64;
        }
        for v in &self.changes {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.pool.is_empty() {
            ::buffa::types::put_shared_bytes_field(1u32, &self.pool, buf);
        }
        for v in &self.changes {
            ::buffa::types::put_len_delimited_header(
                2u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for PoolChangesView<'a> {
    const PACKAGE: &'static str = "uniswap.v3";
    const NAME: &'static str = "PoolChanges";
    const FULL_NAME: &'static str = "uniswap.v3.PoolChanges";
    const TYPE_URL: &'static str = "type.googleapis.com/uniswap.v3.PoolChanges";
}
::buffa::impl_default_view_instance!(PoolChangesView);
::buffa::impl_view_reborrow!(PoolChangesView);
/** Self-contained, `'static` owned view of a `PoolChanges` message.

 Wraps [`::buffa::OwnedView`]`<`[`PoolChangesView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`PoolChangesView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct PoolChangesOwnedView(::buffa::OwnedView<PoolChangesView<'static>>);
impl PoolChangesOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolChangesOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolChangesOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::PoolChanges,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolChangesOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`PoolChangesView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &PoolChangesView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::PoolChanges {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `pool`
    #[must_use]
    pub fn pool(&self) -> &'_ [u8] {
        self.0.reborrow().pool
    }
    /// Field 2: `changes`
    #[must_use]
    pub fn changes(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::PoolChangeView<'_>> {
        &self.0.reborrow().changes
    }
}
impl ::core::convert::From<::buffa::OwnedView<PoolChangesView<'static>>>
for PoolChangesOwnedView {
    fn from(inner: ::buffa::OwnedView<PoolChangesView<'static>>) -> Self {
        PoolChangesOwnedView(inner)
    }
}
impl ::core::convert::From<PoolChangesOwnedView>
for ::buffa::OwnedView<PoolChangesView<'static>> {
    fn from(wrapper: PoolChangesOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<PoolChangesView<'static>>>
for PoolChangesOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<PoolChangesView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::PoolChanges {
    type View<'a> = PoolChangesView<'a>;
    type ViewHandle = PoolChangesOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct PoolChangeView<'a> {
    /// Field 1: `block_log_index`
    pub block_log_index: u32,
    /// Field 2: `ordinal`
    pub ordinal: u64,
    pub change: ::core::option::Option<
        super::super::__buffa::view::oneof::pool_change::Change<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for PoolChangeView<'a> {
    type Owned = super::super::PoolChange;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_log_index = ::buffa::types::decode_uint32(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.ordinal = ::buffa::types::decode_uint64(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                if let Some(
                    super::super::__buffa::view::oneof::pool_change::Change::Initialize(
                        ref mut existing,
                    ),
                ) = view.change
                {
                    ::buffa::MessageView::merge_into_view(
                        &mut **existing,
                        sub,
                        __sub_ctx,
                    )?;
                } else {
                    view.change = Some(
                        super::super::__buffa::view::oneof::pool_change::Change::Initialize(
                            ::buffa::alloc::boxed::Box::new(
                                <super::super::__buffa::view::PoolPriceStateView as ::buffa::MessageView>::decode_view_ctx(
                                    sub,
                                    __sub_ctx,
                                )?,
                            ),
                        ),
                    );
                }
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                if let Some(
                    super::super::__buffa::view::oneof::pool_change::Change::Swap(
                        ref mut existing,
                    ),
                ) = view.change
                {
                    ::buffa::MessageView::merge_into_view(
                        &mut **existing,
                        sub,
                        __sub_ctx,
                    )?;
                } else {
                    view.change = Some(
                        super::super::__buffa::view::oneof::pool_change::Change::Swap(
                            ::buffa::alloc::boxed::Box::new(
                                <super::super::__buffa::view::PoolPriceStateView as ::buffa::MessageView>::decode_view_ctx(
                                    sub,
                                    __sub_ctx,
                                )?,
                            ),
                        ),
                    );
                }
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                if let Some(
                    super::super::__buffa::view::oneof::pool_change::Change::Liquidity(
                        ref mut existing,
                    ),
                ) = view.change
                {
                    ::buffa::MessageView::merge_into_view(
                        &mut **existing,
                        sub,
                        __sub_ctx,
                    )?;
                } else {
                    view.change = Some(
                        super::super::__buffa::view::oneof::pool_change::Change::Liquidity(
                            ::buffa::alloc::boxed::Box::new(
                                <super::super::__buffa::view::PoolLiquidityChangeView as ::buffa::MessageView>::decode_view_ctx(
                                    sub,
                                    __sub_ctx,
                                )?,
                            ),
                        ),
                    );
                }
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                if let Some(
                    super::super::__buffa::view::oneof::pool_change::Change::Invalid(
                        ref mut existing,
                    ),
                ) = view.change
                {
                    ::buffa::MessageView::merge_into_view(
                        &mut **existing,
                        sub,
                        __sub_ctx,
                    )?;
                } else {
                    view.change = Some(
                        super::super::__buffa::view::oneof::pool_change::Change::Invalid(
                            ::buffa::alloc::boxed::Box::new(
                                <super::super::__buffa::view::InvalidPoolChangeView as ::buffa::MessageView>::decode_view_ctx(
                                    sub,
                                    __sub_ctx,
                                )?,
                            ),
                        ),
                    );
                }
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::PoolChange, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::PoolChange, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::PoolChange {
            block_log_index: self.block_log_index,
            ordinal: self.ordinal,
            change: match self.change.as_ref() {
                ::core::option::Option::Some(v) => {
                    ::core::option::Option::Some(
                        match v {
                            super::super::__buffa::view::oneof::pool_change::Change::Initialize(
                                v,
                            ) => {
                                super::super::__buffa::oneof::pool_change::Change::Initialize(
                                    ::buffa::alloc::boxed::Box::new(
                                        v.to_owned_from_source(__buffa_src)?,
                                    ),
                                )
                            }
                            super::super::__buffa::view::oneof::pool_change::Change::Swap(
                                v,
                            ) => {
                                super::super::__buffa::oneof::pool_change::Change::Swap(
                                    ::buffa::alloc::boxed::Box::new(
                                        v.to_owned_from_source(__buffa_src)?,
                                    ),
                                )
                            }
                            super::super::__buffa::view::oneof::pool_change::Change::Liquidity(
                                v,
                            ) => {
                                super::super::__buffa::oneof::pool_change::Change::Liquidity(
                                    ::buffa::alloc::boxed::Box::new(
                                        v.to_owned_from_source(__buffa_src)?,
                                    ),
                                )
                            }
                            super::super::__buffa::view::oneof::pool_change::Change::Invalid(
                                v,
                            ) => {
                                super::super::__buffa::oneof::pool_change::Change::Invalid(
                                    ::buffa::alloc::boxed::Box::new(
                                        v.to_owned_from_source(__buffa_src)?,
                                    ),
                                )
                            }
                        },
                    )
                }
                ::core::option::Option::None => ::core::option::Option::None,
            },
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for PoolChangeView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.block_log_index != 0u32 {
            size
                += 1u64
                    + ::buffa::types::uint32_encoded_len(self.block_log_index) as u64;
        }
        if self.ordinal != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.ordinal) as u64;
        }
        if let ::core::option::Option::Some(ref v) = self.change {
            match v {
                super::super::__buffa::view::oneof::pool_change::Change::Initialize(
                    x,
                ) => {
                    let __slot = __cache.reserve();
                    let inner = x.compute_size(__cache);
                    __cache.set(__slot, inner);
                    size
                        += 1u64 + ::buffa::encoding::varint_len(inner as u64) as u64
                            + inner as u64;
                }
                super::super::__buffa::view::oneof::pool_change::Change::Swap(x) => {
                    let __slot = __cache.reserve();
                    let inner = x.compute_size(__cache);
                    __cache.set(__slot, inner);
                    size
                        += 1u64 + ::buffa::encoding::varint_len(inner as u64) as u64
                            + inner as u64;
                }
                super::super::__buffa::view::oneof::pool_change::Change::Liquidity(
                    x,
                ) => {
                    let __slot = __cache.reserve();
                    let inner = x.compute_size(__cache);
                    __cache.set(__slot, inner);
                    size
                        += 1u64 + ::buffa::encoding::varint_len(inner as u64) as u64
                            + inner as u64;
                }
                super::super::__buffa::view::oneof::pool_change::Change::Invalid(x) => {
                    let __slot = __cache.reserve();
                    let inner = x.compute_size(__cache);
                    __cache.set(__slot, inner);
                    size
                        += 1u64 + ::buffa::encoding::varint_len(inner as u64) as u64
                            + inner as u64;
                }
            }
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.block_log_index != 0u32 {
            ::buffa::types::put_uint32_field(1u32, self.block_log_index, buf);
        }
        if self.ordinal != 0u64 {
            ::buffa::types::put_uint64_field(2u32, self.ordinal, buf);
        }
        if let ::core::option::Option::Some(ref v) = self.change {
            match v {
                super::super::__buffa::view::oneof::pool_change::Change::Initialize(
                    x,
                ) => {
                    ::buffa::types::put_len_delimited_header(
                        3u32,
                        u64::from(__cache.consume_next()),
                        buf,
                    );
                    x.write_to(__cache, buf);
                }
                super::super::__buffa::view::oneof::pool_change::Change::Swap(x) => {
                    ::buffa::types::put_len_delimited_header(
                        4u32,
                        u64::from(__cache.consume_next()),
                        buf,
                    );
                    x.write_to(__cache, buf);
                }
                super::super::__buffa::view::oneof::pool_change::Change::Liquidity(
                    x,
                ) => {
                    ::buffa::types::put_len_delimited_header(
                        5u32,
                        u64::from(__cache.consume_next()),
                        buf,
                    );
                    x.write_to(__cache, buf);
                }
                super::super::__buffa::view::oneof::pool_change::Change::Invalid(x) => {
                    ::buffa::types::put_len_delimited_header(
                        6u32,
                        u64::from(__cache.consume_next()),
                        buf,
                    );
                    x.write_to(__cache, buf);
                }
            }
        }
    }
}
impl<'a> ::buffa::MessageName for PoolChangeView<'a> {
    const PACKAGE: &'static str = "uniswap.v3";
    const NAME: &'static str = "PoolChange";
    const FULL_NAME: &'static str = "uniswap.v3.PoolChange";
    const TYPE_URL: &'static str = "type.googleapis.com/uniswap.v3.PoolChange";
}
::buffa::impl_default_view_instance!(PoolChangeView);
::buffa::impl_view_reborrow!(PoolChangeView);
/** Self-contained, `'static` owned view of a `PoolChange` message.

 Wraps [`::buffa::OwnedView`]`<`[`PoolChangeView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`PoolChangeView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct PoolChangeOwnedView(::buffa::OwnedView<PoolChangeView<'static>>);
impl PoolChangeOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolChangeOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolChangeOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::PoolChange,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolChangeOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`PoolChangeView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &PoolChangeView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::PoolChange {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `block_log_index`
    #[must_use]
    pub fn block_log_index(&self) -> u32 {
        self.0.reborrow().block_log_index
    }
    /// Field 2: `ordinal`
    #[must_use]
    pub fn ordinal(&self) -> u64 {
        self.0.reborrow().ordinal
    }
    /// Oneof `change`.
    #[must_use]
    pub fn change(
        &self,
    ) -> ::core::option::Option<
        &super::super::__buffa::view::oneof::pool_change::Change<'_>,
    > {
        self.0.reborrow().change.as_ref()
    }
}
impl ::core::convert::From<::buffa::OwnedView<PoolChangeView<'static>>>
for PoolChangeOwnedView {
    fn from(inner: ::buffa::OwnedView<PoolChangeView<'static>>) -> Self {
        PoolChangeOwnedView(inner)
    }
}
impl ::core::convert::From<PoolChangeOwnedView>
for ::buffa::OwnedView<PoolChangeView<'static>> {
    fn from(wrapper: PoolChangeOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<PoolChangeView<'static>>>
for PoolChangeOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<PoolChangeView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::PoolChange {
    type View<'a> = PoolChangeView<'a>;
    type ViewHandle = PoolChangeOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct PoolPriceStateView<'a> {
    /// uint160, unscaled Q64.96
    ///
    /// Field 1: `sqrt_price_x96`
    pub sqrt_price_x96: &'a str,
    /// int24, including the zero-for-one boundary convention
    ///
    /// Field 2: `tick`
    pub tick: i32,
    /// uint128; zero for Initialize
    ///
    /// Field 3: `liquidity`
    pub liquidity: &'a str,
}
impl<'a> ::buffa::MessageView<'a> for PoolPriceStateView<'a> {
    type Owned = super::super::PoolPriceState;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.sqrt_price_x96 = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.tick = ::buffa::types::decode_int32(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.liquidity = ::buffa::types::borrow_str(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::PoolPriceState, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::PoolPriceState, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::PoolPriceState {
            sqrt_price_x96: self.sqrt_price_x96.to_string(),
            tick: self.tick,
            liquidity: self.liquidity.to_string(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for PoolPriceStateView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.sqrt_price_x96.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.sqrt_price_x96) as u64;
        }
        if self.tick != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.tick) as u64;
        }
        if !self.liquidity.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.liquidity) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.sqrt_price_x96.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.sqrt_price_x96, buf);
        }
        if self.tick != 0i32 {
            ::buffa::types::put_int32_field(2u32, self.tick, buf);
        }
        if !self.liquidity.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.liquidity, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for PoolPriceStateView<'a> {
    const PACKAGE: &'static str = "uniswap.v3";
    const NAME: &'static str = "PoolPriceState";
    const FULL_NAME: &'static str = "uniswap.v3.PoolPriceState";
    const TYPE_URL: &'static str = "type.googleapis.com/uniswap.v3.PoolPriceState";
}
::buffa::impl_default_view_instance!(PoolPriceStateView);
::buffa::impl_view_reborrow!(PoolPriceStateView);
/** Self-contained, `'static` owned view of a `PoolPriceState` message.

 Wraps [`::buffa::OwnedView`]`<`[`PoolPriceStateView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`PoolPriceStateView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct PoolPriceStateOwnedView(::buffa::OwnedView<PoolPriceStateView<'static>>);
impl PoolPriceStateOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolPriceStateOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolPriceStateOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::PoolPriceState,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolPriceStateOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`PoolPriceStateView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &PoolPriceStateView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::PoolPriceState {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// uint160, unscaled Q64.96
    ///
    /// Field 1: `sqrt_price_x96`
    #[must_use]
    pub fn sqrt_price_x96(&self) -> &'_ str {
        self.0.reborrow().sqrt_price_x96
    }
    /// int24, including the zero-for-one boundary convention
    ///
    /// Field 2: `tick`
    #[must_use]
    pub fn tick(&self) -> i32 {
        self.0.reborrow().tick
    }
    /// uint128; zero for Initialize
    ///
    /// Field 3: `liquidity`
    #[must_use]
    pub fn liquidity(&self) -> &'_ str {
        self.0.reborrow().liquidity
    }
}
impl ::core::convert::From<::buffa::OwnedView<PoolPriceStateView<'static>>>
for PoolPriceStateOwnedView {
    fn from(inner: ::buffa::OwnedView<PoolPriceStateView<'static>>) -> Self {
        PoolPriceStateOwnedView(inner)
    }
}
impl ::core::convert::From<PoolPriceStateOwnedView>
for ::buffa::OwnedView<PoolPriceStateView<'static>> {
    fn from(wrapper: PoolPriceStateOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<PoolPriceStateView<'static>>>
for PoolPriceStateOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<PoolPriceStateView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::PoolPriceState {
    type View<'a> = PoolPriceStateView<'a>;
    type ViewHandle = PoolPriceStateOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct PoolLiquidityChangeView<'a> {
    /// inclusive int24
    ///
    /// Field 1: `tick_lower`
    pub tick_lower: i32,
    /// exclusive int24
    ///
    /// Field 2: `tick_upper`
    pub tick_upper: i32,
    /// signed decimal: Mint positive, Burn negative
    ///
    /// Field 3: `liquidity_delta`
    pub liquidity_delta: &'a str,
}
impl<'a> ::buffa::MessageView<'a> for PoolLiquidityChangeView<'a> {
    type Owned = super::super::PoolLiquidityChange;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.tick_lower = ::buffa::types::decode_int32(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.tick_upper = ::buffa::types::decode_int32(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.liquidity_delta = ::buffa::types::borrow_str(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::PoolLiquidityChange,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::PoolLiquidityChange,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::PoolLiquidityChange {
            tick_lower: self.tick_lower,
            tick_upper: self.tick_upper,
            liquidity_delta: self.liquidity_delta.to_string(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for PoolLiquidityChangeView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.tick_lower != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.tick_lower) as u64;
        }
        if self.tick_upper != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.tick_upper) as u64;
        }
        if !self.liquidity_delta.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.liquidity_delta) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.tick_lower != 0i32 {
            ::buffa::types::put_int32_field(1u32, self.tick_lower, buf);
        }
        if self.tick_upper != 0i32 {
            ::buffa::types::put_int32_field(2u32, self.tick_upper, buf);
        }
        if !self.liquidity_delta.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.liquidity_delta, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for PoolLiquidityChangeView<'a> {
    const PACKAGE: &'static str = "uniswap.v3";
    const NAME: &'static str = "PoolLiquidityChange";
    const FULL_NAME: &'static str = "uniswap.v3.PoolLiquidityChange";
    const TYPE_URL: &'static str = "type.googleapis.com/uniswap.v3.PoolLiquidityChange";
}
::buffa::impl_default_view_instance!(PoolLiquidityChangeView);
::buffa::impl_view_reborrow!(PoolLiquidityChangeView);
/** Self-contained, `'static` owned view of a `PoolLiquidityChange` message.

 Wraps [`::buffa::OwnedView`]`<`[`PoolLiquidityChangeView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`PoolLiquidityChangeView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct PoolLiquidityChangeOwnedView(
    ::buffa::OwnedView<PoolLiquidityChangeView<'static>>,
);
impl PoolLiquidityChangeOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolLiquidityChangeOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolLiquidityChangeOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::PoolLiquidityChange,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolLiquidityChangeOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`PoolLiquidityChangeView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &PoolLiquidityChangeView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::PoolLiquidityChange {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// inclusive int24
    ///
    /// Field 1: `tick_lower`
    #[must_use]
    pub fn tick_lower(&self) -> i32 {
        self.0.reborrow().tick_lower
    }
    /// exclusive int24
    ///
    /// Field 2: `tick_upper`
    #[must_use]
    pub fn tick_upper(&self) -> i32 {
        self.0.reborrow().tick_upper
    }
    /// signed decimal: Mint positive, Burn negative
    ///
    /// Field 3: `liquidity_delta`
    #[must_use]
    pub fn liquidity_delta(&self) -> &'_ str {
        self.0.reborrow().liquidity_delta
    }
}
impl ::core::convert::From<::buffa::OwnedView<PoolLiquidityChangeView<'static>>>
for PoolLiquidityChangeOwnedView {
    fn from(inner: ::buffa::OwnedView<PoolLiquidityChangeView<'static>>) -> Self {
        PoolLiquidityChangeOwnedView(inner)
    }
}
impl ::core::convert::From<PoolLiquidityChangeOwnedView>
for ::buffa::OwnedView<PoolLiquidityChangeView<'static>> {
    fn from(wrapper: PoolLiquidityChangeOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<PoolLiquidityChangeView<'static>>>
for PoolLiquidityChangeOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<PoolLiquidityChangeView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::PoolLiquidityChange {
    type View<'a> = PoolLiquidityChangeView<'a>;
    type ViewHandle = PoolLiquidityChangeOwnedView;
}
/// A recognized topic with an invalid shape/value. Consumers must invalidate this
/// pool rather than silently carry its previous state. No raw payload is copied.
#[derive(Clone, Debug, Default)]
pub struct InvalidPoolChangeView<'a> {
    /// Field 1: `event_name`
    pub event_name: &'a str,
}
impl<'a> ::buffa::MessageView<'a> for InvalidPoolChangeView<'a> {
    type Owned = super::super::InvalidPoolChange;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.event_name = ::buffa::types::borrow_str(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::InvalidPoolChange, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::InvalidPoolChange, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::InvalidPoolChange {
            event_name: self.event_name.to_string(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for InvalidPoolChangeView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.event_name.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.event_name) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.event_name.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.event_name, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for InvalidPoolChangeView<'a> {
    const PACKAGE: &'static str = "uniswap.v3";
    const NAME: &'static str = "InvalidPoolChange";
    const FULL_NAME: &'static str = "uniswap.v3.InvalidPoolChange";
    const TYPE_URL: &'static str = "type.googleapis.com/uniswap.v3.InvalidPoolChange";
}
::buffa::impl_default_view_instance!(InvalidPoolChangeView);
::buffa::impl_view_reborrow!(InvalidPoolChangeView);
/** Self-contained, `'static` owned view of a `InvalidPoolChange` message.

 Wraps [`::buffa::OwnedView`]`<`[`InvalidPoolChangeView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`InvalidPoolChangeView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct InvalidPoolChangeOwnedView(
    ::buffa::OwnedView<InvalidPoolChangeView<'static>>,
);
impl InvalidPoolChangeOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            InvalidPoolChangeOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            InvalidPoolChangeOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::InvalidPoolChange,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            InvalidPoolChangeOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`InvalidPoolChangeView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &InvalidPoolChangeView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::InvalidPoolChange {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `event_name`
    #[must_use]
    pub fn event_name(&self) -> &'_ str {
        self.0.reborrow().event_name
    }
}
impl ::core::convert::From<::buffa::OwnedView<InvalidPoolChangeView<'static>>>
for InvalidPoolChangeOwnedView {
    fn from(inner: ::buffa::OwnedView<InvalidPoolChangeView<'static>>) -> Self {
        InvalidPoolChangeOwnedView(inner)
    }
}
impl ::core::convert::From<InvalidPoolChangeOwnedView>
for ::buffa::OwnedView<InvalidPoolChangeView<'static>> {
    fn from(wrapper: InvalidPoolChangeOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<InvalidPoolChangeView<'static>>>
for InvalidPoolChangeOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<InvalidPoolChangeView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::InvalidPoolChange {
    type View<'a> = InvalidPoolChangeView<'a>;
    type ViewHandle = InvalidPoolChangeOwnedView;
}
