// @generated by buffa-codegen. DO NOT EDIT.
// source: uniswap-v3-pool-state.proto

pub mod pool_change {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum Change<'a> {
        Initialize(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::PoolPriceStateView<'a>,
            >,
        ),
        Swap(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::PoolPriceStateView<'a>,
            >,
        ),
        Liquidity(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::PoolLiquidityChangeView<'a>,
            >,
        ),
        Invalid(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::InvalidPoolChangeView<'a>,
            >,
        ),
    }
}
