// @generated by buffa-codegen. DO NOT EDIT.
// source: uniswap-v3-pool-state.proto

pub mod pool_change {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    pub enum Change {
        Initialize(::buffa::alloc::boxed::Box<super::super::super::PoolPriceState>),
        Swap(::buffa::alloc::boxed::Box<super::super::super::PoolPriceState>),
        Liquidity(::buffa::alloc::boxed::Box<super::super::super::PoolLiquidityChange>),
        Invalid(::buffa::alloc::boxed::Box<super::super::super::InvalidPoolChange>),
    }
    impl ::buffa::Oneof for Change {}
    impl From<super::super::super::PoolLiquidityChange> for Change {
        fn from(v: super::super::super::PoolLiquidityChange) -> Self {
            Self::Liquidity(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::PoolLiquidityChange>
    for ::core::option::Option<Change> {
        fn from(v: super::super::super::PoolLiquidityChange) -> Self {
            Self::Some(Change::from(v))
        }
    }
    impl From<super::super::super::InvalidPoolChange> for Change {
        fn from(v: super::super::super::InvalidPoolChange) -> Self {
            Self::Invalid(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::InvalidPoolChange>
    for ::core::option::Option<Change> {
        fn from(v: super::super::super::InvalidPoolChange) -> Self {
            Self::Some(Change::from(v))
        }
    }
}
